### ISSUE TITLE
[BUG] Drafts - types are missing draft-management fields

### ISSUE THREAD

**Issue by geert-janklaps** [cap-js/cds-typer#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

We're in the process of migrating our existing types generated with version 0.5.0 to the new typer functionality. Since this update types have become more strict which now seems to be causing issues when trying to work with drafts entities. (e.g. inserting additional draft data through code)

Each draft entity has four fields for draft management:
- DraftAdministrativeData_DraftUUID
- HasDraftEntity
- HasActiveEntity
- IsActiveEntity

Currently it seems like these fields are not covered by the typer functionality.

### Expected Behavior

Having these administrative fields available, so we can access the draft_uuid to e.g. add additional entities to a composition through code.

### Environment

```markdown
OS: Business application studio
Versions:
@cap-js/cds-typer: 0.11.1
@cap-js/db-service: 1.3.2
@cap-js/sqlite: 1.3.1
@sap/cds: 7.3.1
@sap/cds-common-content: 1.2.0
@sap/cds-compiler: 4.3.2
@sap/cds-dk: 7.3.1
@sap/cds-dk (global): 7.3.1
@sap/cds-fiori: 1.1.0
@sap/cds-foss: 4.0.2
@sap/cds-hana: 2.0.0
@sap/cds-mtxs: 1.12.1
@sap/eslint-plugin-cds: 2.6.3
Node.js: v18.14.2
```

**Comment by daogrady** [comment]
Hi Geert-Jan,

thank you for reporting this issue. Draftability itself is a bit fragile in cds-typer and will require a rework somewhere down the line. As I am not very familiar with drafts myself, could you maybe provide a minimal working sample where I could observe these four missing fields? I fail to find them anywhere in the compiled CSN.

Best,
Daniel
