### ISSUE TITLE
[BUG] Types for CDS models with namespace from separate node module get wrongly generated

### ISSUE THREAD

**Issue by geert-janklaps** [cap-js/cds-typer#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Currently it seems like types for CDS models from separate node modules that are using namespaces get wrongly generated.
The import is generated as follows: import * as _<namespace> from ... 
The types used seem to be missing the namespace prefix as seen in below example: 
![image](https://github.com/cap-js/cds-typer/assets/2744548/ace45045-196b-4b3a-ae3b-a19d429f1ae2)

Fixing this manually as below, solves the issue:
![image](https://github.com/cap-js/cds-typer/assets/2744548/f15d45e5-3fb2-48b6-87cc-d176652166e5)

### Expected Behavior

Generated types should include the prefix as generated in the import

### Environment

```markdown
OS: Business Application Studio
CDS versions:
@cap-js/cds-typer: 0.11.1
@cap-js/db-service: 1.3.2
@cap-js/sqlite: 1.3.1
@sap/cds: 7.3.1
@sap/cds-common-content: 1.2.0
@sap/cds-compiler: 4.3.2
@sap/cds-dk: 7.3.1
@sap/cds-dk (global): 7.3.1
@sap/cds-fiori: 1.1.0
@sap/cds-foss: 4.0.2
@sap/cds-hana: 2.0.0
@sap/cds-mtxs: 1.12.1
@sap/eslint-plugin-cds: 2.6.3
Node.js: v18.14.2
```

**Comment by daogrady** [comment]
Hi Geert-Jan,

thank you for reporting this issue! I don't think I fully understand what you mean by "CDS models from separate node modules". Could you please attach a sample repository or steps to reproduce with a minimal model?

Best,
Daniel
