### ISSUE TITLE
cds.test + cds-typer + ts

### ISSUE THREAD

**Issue by dragolea** [cap-js/cds-typer#110]
### Question

Hi,
I am testing a project developed using TS and cds-typer.
Currently, the cds-typer produces TS & JS files and somehow jest doesn't like something in the JS files.

Do you know how we can test CDS-typer generated entities with Jest on TS projects?
Currently on SAP CAP cds.test docu, I was not able to find something useful for test cds-typer with TS>

```ts
  ● Test suite failed to run

    TypeError: cds.entities is not a function

      1 | // This is an automatically generated file. Please do not change its contents manually!
      2 | const cds = require('@sap/cds')
    > 3 | const csn = cds.entities('CatalogService')
        |                 ^
      4 | module.exports = { name: 'CatalogService' }
      5 | module.exports.BookEvent = csn.BookEvents
      6 | module.exports.BookEvents = csn.BookEvents
```

cds-typer version : 0.11.1
npm : 9.8.0
node : 21.1.0

OS : Macosx 

let me know if you need further info

**Comment by daogrady** [comment]
Hi Daniel,

do you maybe have a repository where I can observe that behaviour? I will then gladly have a look at it.

Best,
Daniel

**Comment by dragolea** [comment]
Hi Dao,

Repository
```bash
git clone https://github.com/dragolea/cds-typer-ts-test.git
```

Steps:
```bash
npm install
npm test
```

The test command looks like `"test": "npm run build:entities --prefix test/bookshop && jest"``

I am building the entities on the fly and `build:entities` can be found in **./test/bookshop package.json**
- "build:entities": "cds-typer '*' --outputDirectory ./srv/util/types/entities"

**Comment by dragolea** [comment]
Thanks @daogrady, really appreciate your help.
