### ISSUE TITLE
[BUG] "excluding" clause in CDS projections not applied for compiled TS models

### ISSUE THREAD

**Issue by siarhei-murkou** [cap-js/cds-typer#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Example:

```cds
namespace sap.testmodels;

entity TestObjects {
    key ID: UUID;
    name: String not null;
    description: String;
    dependencies: Association to many ...;
    ...
}
```

```cds
using sap.testmodels as db from '../db';

service TestService {
    entity TestObjects as projection on db.TestObjects excluding { dependencies };
}
```

The CDS entities above are compiled to

```TypeScript
class TestObjects {
    ID: string;
    name: string;
    description: string | null;
    dependencies: Association.to.many<...>;
}
```

### Expected Behavior

Compiled TypeScript models should leave out properties which are marked as excluded on CDS layer.

```TypeScript
class TestObjects {
    ID: string;
    name: string;
    description: string | null;
}
```

### Environment

```markdown
- **OS**: MacOS 14.1.1
- **Node**: 18.18.2
- **npm**: 9.8.1
- **cds-typer**: 0.12.0
- **cds**: 7.3.1
```

### Anything else?

Absolutely the same result if to use explicit select of certain properties. For example:
```cds
using sap.testmodels as db from '../db';

service TestService {
    entity TestObjects as projection on db.TestObjects { ID, name, description as desc };
}
```

**Comment by daogrady** [comment]
Hi Siarhei,

thank you for reporting this gap! It will be fixed in https://github.com/cap-js/cds-typer/pull/118
Feel free to check the PR out on your model before I merge it.

Best,
Daniel

**Comment by siarhei-murkou** [comment]
Hi Daniel,
Thank you for fixing it quite quickly! 🙂 

The fix works fine for me, so PR can be merged. 👍
