### ISSUE TITLE
[BUG] Runtime import issue with String Enums

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-typer#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Right now we're encountering runtime issues when importing specific namespaces / entities.

Given an entity such as this:

```
namespace com.someThing.someThingElse;

entity someElements {
  key guid : String;
  key someAssignment  : Association to Assignments;
 someStringEnum : String enum {
   someEnum
 };
}
```

Typer creates within `@cds-models/com/someThing/someThingElse/index.js` something such as:
```
[...]

// enums
module.exports.com.someThing.someThingElse.someElements = { someEnum: "someEnum"}
```

Trying to import this or another element exposed in that service / namespace during runtime such as:
```
const { someElements } = await import('#cds-models/com/someThing/someThingElse')
```

An error like the following is thrown:
```
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'someThing')
  at Object.<anonymous> (.../@cds-models/com/someThing/someThingElse/index.js:13:20)     
  at Module._compile (node:internal/modules/cjs/loader:1376:14)     
  at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1618:23)     
  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)     
  at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)     
  at Module.load (node:internal/modules/cjs/loader:1207:32)     
  at Function.Module._load (node:internal/modules/cjs/loader:1023:12)     
  at cjsLoader (node:internal/modules/esm/translators:345:17)     
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)     
  at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
 ```
 
Removing the line `module.expots.com.someThing.someThingElse.someElements = { someEnum: "someEnum"}` solves the issue on the import (yet removing something manually with unknown impacts might not be optimal.
 
 Also changing the entity definition to
 
 ```
namespace com.someThing.someThingElse;

entity someElements {
  key guid : String;
  key someAssignment  : Association to Assignments;
// someStringEnum : String enum {
//   someEnum
//  };
}

```

Resolves the issue on import .

### Expected Behavior

You should be able to runtime import without issues even when String Enums are available.

### Environment

```markdown
- **OS**: MacOs
- **Node**: v20.10.0.
- **npm**:
- **cds-typer**: 0.13.0
- **cds**:7.4.2
```

**Comment by daogrady** [comment]
Hi Tobias,

thanks for reporting this issue! 
The problem was actually twofold and the solution to this might be a bit finicky, as it only works for most cases.
cds-typer will now generate these inline-enums as follow:

```js
// com/someThing/index.js
module.exports.someElements.someStringEnum  ??= ...
```

This removes the leading namespace, which is already represented via the file structure. But it also introduces a coalescing assignment, as users could potentially break their runtime artefacts by creating an enum called `actions` or another property that is already present in the runtime CSN of entities. To preserve all current behaviour, the assignment is then skipped. If you'd like you can give the PR a whirl before I merge it.

Best,
Daniel
