### ISSUE TITLE
[BUG] Action with string enum input parameter results in an incorrect type

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-typer#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Given an action such as:

```
    action   test( @mandatory testInput : String not null enum {
        anEntry;
    })
```

Yields a type like:
```
export declare const test: { (testInput: test_testInput): {} | null, __parameters: {testInput: test_testInput}, __returns: {} | null };
```

With TypeScript complaining:

```
Cannot find name 'test_testInput'.ts(2304)
Exported variable 'test' has or is using private name 'test_testInput'.ts(4025)
```

### Expected Behavior

I'd expect a correct type returned from the creation.

### Environment

```markdown
- **OS**: MacOs
- **Node**: v20.10.0.
- **npm**:
- **cds-typer**: 0.13.0
- **cds**:7.4.2
```

**Comment by daogrady** [comment]
Hi Tobias,

thanks for reporting this use case!
I am actually not even sure where this enum would supposed to be generated to. So I guess 

```ts
        test: { (testInput: 'someEntry'): any, __parameters: {testInput: 'someEntry'}, __returns: any }
```

would be the best option here?

Best,
Daniel

**Comment by tsteckenborn** [comment]
Would suffice for me. In the end also `string` would be fine for me - everything is better then a typ error 😅.

**Comment by daogrady** [comment]
That's reasonable, so I'll see to make it one of the two.
