### ISSUE TITLE
[BUG] Imported remote service type generation fails

### ISSUE THREAD

**Issue by geert-janklaps** [cap-js/cds-typer#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Hi,

When importing the SAP Build Process Automation workflow runtime API from the Business Accelerator HUB, the cds-typer crashes with following error log:
![image](https://github.com/cap-js/cds-typer/assets/2744548/be49b809-a1fb-4a9e-9c73-47fdde9d201b)

Original file from SAP Business Accelerator HUB: [SPA_Workflow_Runtime.json](https://github.com/cap-js/cds-typer/files/13784235/SPA_Workflow_Runtime.json)

Import commands tried: 
cds-ts import SPA_Workflow_Runtime.json --from openapi
cds-ts import SPA_Workflow_Runtime.json --from openapi --as cds

Both resulting in the same error. (both generated files csn / cds are syntactically correct)
Once this service is imported this renders the cds-typer unsuable, automatic type generation using the VS Code plugin always crashes.

Cheers,
Geert-Jan

### Expected Behavior

cds-typer not to crash and generate the types successfully.

### Steps To Reproduce

Described in current behavior

### Environment

```markdown
OS: Windows 11 Pro
Node.js: v20.10.0
CDS versions:
@cap-js/cds-typer: 0.15.0
@cap-js/cds-types: 0.1.0
@cap-js/sqlite: 1.4.0
@sap/cds: 7.5.1
@sap/cds-common-content: 1.3.1
@sap/cds-compiler: 4.5.0
@sap/cds-dk: 7.5.0
@sap/cds-dk (global): 7.5.0
@sap/cds-fiori: 1.2.2
@sap/cds-foss: 5.0.0
@sap/cds-hana: 2.0.0
@sap/cds-mtxs: 1.14.1
@sap/eslint-plugin-cds: 2.6.4
```

**Comment by daogrady** [comment]
Hi Geert-Jan,

I have created a [PR](https://github.com/cap-js/cds-typer/pull/150) that addresses this issue. I noticed there is another problem hidden in there where top-level functions within a service do not receive a proper type, but with this fix cds-typer should at least no longer crash and generate working types for the SPA_Workflow_Runtime.json you provided.
Please let me know if you can confirm this fixes the problem before I merge.

Best
Daniel
