### ISSUE TITLE
[BUG] Path with spaces crash the type generation process in windows

### ISSUE THREAD

**Issue by prophet1906** [cap-js/cds-typer#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When the project path contains spaces in Windows it crashes the type generation.
Sample logs shared below:

```
Node.js v20.9.0
CDSError: Could not (re)generate types for model. Could not read file content of *: Failed: node C:\Users\<i-number>\foo bar\project\node_modules\@cap-js\cds-typer\lib\cli.js "*" --outputDirectory "C:\Users\<i-number>\foo bar\project\@cds-models"
<exit code:>
1
<stderr:>
node:internal/modules/cjs/loader:1051
  throw err;
  ^
 
Error: Cannot find module 'C:\Users\<i-number>\foo'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Expected Behavior

Type generation should work as expected.

### Steps To Reproduce

1. Create a cap project with typescript.
2. Add a simple entity
3. Move your project folder to a path with spaces
4. Try saving CDS file and check the output logs in CDS channel
5. Type generation fails

### Environment

```markdown
- **OS**: Windows
- **Node**:
- **npm**:
- **cds-typer**: 0.15.0
- **cds**:
```

**Comment by daogrady** [comment]
Hi Shubham,

thanks for pointing this out! You can fix this locally by going into your VSCode settings and adding quotes around the binary path:
![Screenshot 2024-01-08 at 15 09 58](https://github.com/cap-js/cds-typer/assets/103028279/7f91be77-87fe-4132-85c4-b66c96bfc527)

Best,
Daniel

**Comment by daogrady** [comment]
The next version of the VSCode extension will add quotes around the binary path by default.
