### ISSUE TITLE
[BUG] CDS type aliasing causes duplicate TS type definitions

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-typer#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

If you have type aliasing definitions in your cds schema like the following:
```cds
entity Countries {
    key code : String(2);
        name : String(255);
}

type Country  : Association to Countries;
```

`cds-typer` will generate duplicate definitions:
```ts
export type Country = __.Association.to<Country>;
export function _CountryAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Country extends Base {
        code?: string | null;
        name?: string | null;
      static actions: {
    }
  };
}
export class Country extends _CountryAspect(__.Entity) {}
```

`Country` here is defined both as a `type` and a `class`:
```ts
export type Country = __.Association.to<Country>;
export class Country extends _CountryAspect(__.Entity) {}
```

This obviously causes TypeScript errors:
```
index.ts:4:13 - error TS2300: Duplicate identifier 'Country'.

4 export type Country = __.Association.to<Country>;
```

### Steps To Reproduce

Generate definitions for the following cds schema and then try to use it in your TS code:
```cds
entity Countries {
    key code : String(2);
        name : String(255);
}

type Country  : Association to Countries;
```

### Environment

```markdown
- **OS**: Windows 10
- **Node**: 18.17.1
- **yarn**: 4.0.2
- **cds-typer**: 0.15.0
- **cds**: 7.5.1
```

**Comment by daogrady** [comment]
Hi Tomas,

thank you for pointing out this scenario! cds-typer can detect this behaviour and will actually call it out and suggest a solution when the log level is set to `ERROR`:

```sh
> cds-typer model.cds --outputDirectory /tmp --logLevel ERROR
[ERROR] Derived singular 'Country' for your entity 'Countries', already exists. The resulting types will be erronous. Please consider using '@singular:'/ '@plural:' annotations in your model to resolve this collision.
```

So you can overcome this ambiguity by explicitly adding a singular name for `Countries`, e.g.

```cds
@singular "Country_"
entity Countries {
    key code : String(2);
        name : String(255);
}
```

But I will consider setting the default output level for cds-typer to `ERROR` so people will be able to see these messages more easily.

Best,
Daniel

**Comment by hakimio** [comment]
Yeah, invisible errors is not great...
Anyway, is there any way to tell `cds-typer` not to generate type definitions for the aliased type or rename it? I don't want to change the class `Country` name. I want to either get rid of or rename the following type:
```ts
export type Country = __.Association.to<Country>;
```

**Comment by daogrady** [comment]
There is no way to do this kind of renaming or pass in a forbid-list as of today. We're trying to keep the generated types as close to the actual model as possible, so doing a lot of renames, past the necessary means to specify inflection, would not bode well.

Is renaming that alias within your model an option?

```cds
entity Countries {
    key code : String(2);
        name : String(255);
}

type AssociatedCountry  : Association to Countries;
```

**Comment by hakimio** [comment]
That's a dirty hack you have to remember to do when defining all your type aliases just because of an issue with the `cds-typer`. Honestly, I don't think any of the suggested workarounds/hacks are good solutions. This should be handled properly on `cds-typer` side: given a valid CDS schema, cds-typer should always generate valid TS definitions and user should not be required to do some schema hacks to get proper TS definitions.

**Comment by daogrady** [comment]
What solution do you suggest to resolve this naming collision?

**Comment by hakimio** [comment]
Automatically rename cds type aliases when there is a name collision with an entity name. Leave entity name as is.
Sth like the following:
```ts
export type CountryAssociation = __.Association.to<Country>;
export class Country extends _CountryAspect(__.Entity) {}
```

**Comment by daogrady** [comment]
I don't see how this is less of a hack or should be automatically generated. Your `type` happens to be an alias for an association, yes. But types can be anything, not just associations/ compositions.
How would you automatically derive a name for this collision:

```cds
entity Countries {}
type Country: {
  id: Integer;
}
```
?

**Comment by hakimio** [comment]
Error in your example case, automatically rename or just exclude when the type is an association to the same entity.
Also, adding annotation to allow user to rename any generated type in TS definitions, not only entity, might be a good idea.

**Comment by daogrady** [comment]
Adding an annotation to allow users to rename CDS `type`s would suffer from the same shortcomings you mentioned above: the user has to remember to do it. And if they have to explicitly give it another name, why not just rename it within the model to assert consistency between model and generated types?

**Comment by hakimio** [comment]
Keeping the original type name in the definition results in a nice and clean schema:
```cds
entity Addresses : cuid {
    street     : String(255);
    country    : Country;
    city       : String(255);
    postalCode : String(50);
}
```
vs sth like the following just for cds-typer:
```cds
entity Addresses : cuid {
    street     : String(255);
    country    : CountryAssociation;
    city       : String(255);
    postalCode : String(50);
}
```

I don't want to use this type alias in my TS code, it's only for use in CDS schema to make it look good.

**Comment by hakimio** [comment]
Maybe ability to exclude types and entities from definition using cds annotations could be an option?

**Comment by hakimio** [comment]
SAP itself defines countries and currencies the same way in their "common" definitions:
```
type Country : Association to sap.common.Countries;
entity Countries : CodeList {
    key code : String(3) @(title : '{i18n>CountryCode}');
  }
```

but somehow this doesn't cause the same issue in [the generated TS definition](https://github.com/dxfrontier/cds-ts-samples/blob/46c72a6e4663df6b2d62c18d9d67c665e8db3a62/%40cds-models/sap/common/index.ts#L68).

**Comment by hakimio** [comment]
Ok, moving the definition to a different file works for me. Maybe you should include this suggestion in the error message?

**Comment by daogrady** [comment]
Sure, that won't be an issue!
