### ISSUE TITLE
[QUESTION] How to integrate cds-typer into the CI

### ISSUE THREAD

**Issue by mcastrup** [cap-js/cds-typer#142]
### Question

I have problems to integrate cds-typer in our CI process. I already had a look at the [documentation ](https://cap.cloud.sap/docs/tools/cds-typer#integrate-into-your-ci) and I also tried to adapt the mta.yaml file. However, I always get an error like
`Error: lib/masterData/businessPartners/DbBusinessPartnerRepository.ts(17,38): error TS2307: Cannot find module '#cds-models/sap/erp4sme/c4b/masterData/businessPartners' or its corresponding type declarations.`
in the build process of the pipeline.

The build job on github is defined in our [pr_voter.yml](https://github.tools.sap/erp4sme/crypto-for-business/blob/switch_to_typer_prototype/.github/workflows/pr_voter.yml#L39) file. Here, `npm run build` is executed.
Thus, I added to the build script in the [package.json](https://github.tools.sap/erp4sme/crypto-for-business/blob/switch_to_typer_prototype/package.json#L100) the script:
`"cds-typer": "npx @cap-js/cds-typer \"*\" --outputDirectory @cds-models && npx @cap-js/cds-typer \"*\" --outputDirectory gen/srv/@cds-models",`
I tried several options and finally decided to run cds-typer twice, once with the output directory `@cds-models` and once with `gen/srv/@cds-models`. But the result is always the same: the error mentioned above.

E.g. the generated types cannot be found in the file [DbBusinessPartnerRepository.ts](https://github.tools.sap/erp4sme/crypto-for-business/blob/switch_to_typer_prototype/lib/masterData/businessPartners/DbBusinessPartnerRepository.ts#L17).

Locally in Visual Studio Code, everything works fine.

It would be great if you can have a look at our [repository ](https://github.tools.sap/erp4sme/crypto-for-business/tree/switch_to_typer_prototype) and the [PR error](https://github.tools.sap/erp4sme/crypto-for-business/actions/runs/4460158/job/16507740?pr=2392) and give some advice. If needed, we can schedule a meeting.

Thanks and best regards,
Michael

**Comment by daogrady** [comment]
Hi Michael,

thanks for bringing up this issue. I checked your repository and the tsconfig.json appears to be missing the aliasing for `#cds.models`. Running `cds add typer` should add this section automatically. Does adding this section help?

Best,
Daniel

**Comment by mcastrup** [comment]
Hi Daniel,

finally, I noticed that we have besides the tsconfig.json also a [tsconfig.deploy.json](https://github.tools.sap/erp4sme/crypto-for-business/blob/switch_to_typer_prototype/tsconfig.deploy.json#L17) file. I added the path alias also to this file. The above mentioend errors are gone now. :-)

Please thinks about to include this informatuion also into your documentation. And the `cds add typer` command should also take care of such a tsconfig.deploy.json file.

Best regards,
Michael

**Comment by daogrady** [comment]
Hi Michael,

glad you could fix the issue!

Best,
Daniel
