### ISSUE TITLE
[FEATURE] Generate types also for projections

### ISSUE THREAD

**Issue by mcastrup** [cap-js/cds-typer#155]
### Description

This request is related to my previous question https://github.com/cap-js/cds-typer/issues/121, in which I requested to generate types not only for 'base' entities, but also for views.
Now, I noticed that types are still not generated for projections, like e.g. (see file [Payments.cds](https://github.tools.sap/erp4sme/crypto-for-business/blob/main/db/payment/payments/Payments.cds#L96))
```
@readonly
@plural: 'TotalBalancesPerAccount'
entity TotalBalancePerAccount    as
    projection on WalletAssetTotals {
        key accountId,
            coalesce(
                sum(total), 0
            ) as total : Decimal,
    }
    group by
        accountId;
```

### Suggested Solution

Please take care also of projections.

**Comment by willemi069808** [comment]
It would be good to have this. As a workaround for now, I add the projected properties as virtual properties to my entity. But if this virtual property is not a primitive type (but e.g. an association to an entity) this can't be marked as 'virtual' anymore so you'll end up with a whole bunch or null columns in your database. So the workaround still works, but it gets 'messy'.

**Comment by daogrady** [comment]
Is this issue different from https://github.com/cap-js/cds-typer/issues/81?

**Comment by mcastrup** [comment]
I think, it is the same issue as https://github.com/cap-js/cds-typer/issues/81

**Comment by daogrady** [comment]
Thanks for reporting back on this, let's close this as a duplicate then. This issue should still stay referenced in #81.

**Comment by mcastrup** [comment]
Hi Daniel,

yes, it looks good. :-)

Best regards,
Michael
