### ISSUE TITLE
[BUG] Projection on view does not have correct fields

### ISSUE THREAD

**Issue by nils** [cap-js/cds-typer#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

A [projection on top of a view](https://github.com/cap-js/cds-typer/blob/8bad82be660dcd1961828654035d1bd1a3d62969/test/unit/files/views/model.cds#L1) does not have the correct properties in the TS aspect.

PR #166 contains new unit tests illustrating the issue.

```cds
entity FooViewProjection as
    projection on FooView {
        id as IdProjected,
        alias as AliasProjected
    };
```
is compiled to something similar to
```typescript
return class FooViewProjection extends Base {
  id?: number | null;
  code?: string | null;
  flag?: boolean | null;
  [...]
}
```

### Expected Behavior

The generated TS should rather look similar to this:
```typescript 
class FooViewProjection extends Base {
  IdProjected: number | null;
  AliasProjected?: string | null;
  [...]
}
```

### Environment

```markdown
- **OS**: Linux/arm64 in docker
- **Node**: v18.19.1
- **npm**: 10.2.4
- **cds-typer**: main branch
- **cds**:
@sap/cds: 7.3.1
@sap/cds-compiler: 4.3.2
@sap/cds-dk (global): 7.3.2
@sap/cds-fiori: 1.1.0
@sap/cds-foss: 4.0.2
@sap/cds-mtxs: 1.12.1
@sap/eslint-plugin-cds: 2.6.3
Node.js: v18.19.1
```

### Repository Containing a Minimal Reproducible Example

See (failing) test cases in #166 

### Anything else?

Might be related to #155 #81.

**Comment by daogrady** [comment]
Hi Nils,

I prepared a PR to address issues with projections: https://github.com/cap-js/cds-typer/pull/175
Would you like to give the changes a go and see if it solves the problems you encountered?

Best,
Daniel
