### ISSUE TITLE
Unexpected token '?' when using with the "SAP CDS Language Support"

### ISSUE THREAD

**Issue by xucong-zhan** [cap-js/cds-typer#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

JavaScript

### Current Behavior

When editing a `.cds` file, trying to invoke any code completion such as hitting Ctrl+. after `@UI.` will fail with the following error message in CDS output channel:

```sh
CDSError: Could not (re)generate types for model. Could not read file content of *: Failed: node "/SAPDevelop/Work/ptm-lib-srv/node_modules/@cap-js/cds-typer/lib/cli.js" "*" --outputDirectory "/SAPDevelop/Work/ptm-lib-srv/@cds-models"
<exit code:>
1
<stderr:>
/SAPDevelop/Work/ptm-lib-srv/node_modules/@cap-js/cds-typer/lib/cli.js:92
        outputDirectory: [args.named.outputDirectory, args.named.rootDir].find(d => d !== './') ?? './',
                                                                                                 ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

And other IntelliSense features, like hover for docs, also stop working.

### Expected Behavior

All code actions and IntelliSense features should work for `.cds` files.

### Steps To Reproduce

1. Pull down the `fiori-elements-feature-showcase` project from [here](https://github.com/SAP-samples/fiori-elements-feature-showcase)
2. Install the latest `@cap-js/cds-typer` and use the latest release of "SAP CDS Language Support"
3. Try edit any CDS files

### Environment

```markdown
- **OS**: Ubuntu 22.04
- **Node**: 18.16.0 & 20.11.0 
- **npm**: 9.5.1 & 10.2.4
- **cds-typer**: 0.16.0
- **cds**: 7.3.1
```

### Anything else?

The project I am working on is a standard CAP Java project with Fiori Elements.

It seems many ES6 features are not supported. If I fix the issue of nullish coalescing, there will be errors reported on optional chaining usages.

**Comment by daogrady** [comment]
Hi @xucong-zhan,

I tried your reproduction using SAP CDS Language Support v7.6.1 and cds-typer 0.16.0 and the types were generated just fine.
The problem reads like the nullish coalescing operator `??` is causing issues in your case. The operator has been introduced into Node 14.0.0 so it reads like you are accidentally using a rather old Node version to execute the plugin.
Are you maybe using `nvm`? What is the output of `node -v` run at your home directory (outside of your project's directory!).

Best,
Daniel

**Comment by xucong-zhan** [comment]
Oh... I found the issue...
Yes, I am using `fnm` to manage multiple Node.js installations, and that blinds me to the system Node.js installation at `/usr/bin/node`, which in the case of Ubuntu 22.04 is of version 12.22.9.
Thanks for the prompt response and the useful tip!
