### ISSUE TITLE
[BUG] Type Generation for `Composition of many` erroneous in specific cases (regression between 0.15 and 0.18.1)

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-typer#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Currently it seems as if there's an erroneous generation behaviour in case the derived plural of a property is equal to the derived singular of a property. When the `__.Composition.of.many<Namespace.propertyName>` is generated, it - in specific cases - refers no to the arrayed version (plural) but the singular.

### Expected Behavior

I'd expect the generated types to not have type errors.

### Steps To Reproduce

Given an entity such as:

```
entity UserInterfaces : cuid, managed {
[...]
     usageStatus                    : Composition of many {
                                                    [...]
                                                };
[...]
    intentMapping                  : Composition of many {
                                                   [...]
                                                };
[...]
}
```

The generated types look like this:

![2024-03-18 at 08 00 06](https://github.com/cap-js/cds-typer/assets/50519619/f6bce7af-8a03-45e1-aa4b-6a63906ed37a)

So at first glimpse both look identical, but the `intentMapping` one is reporting an error.

Looking at the generated referenced classes you can notice, that for the (correct) one it's referring to the plural `usageStatus extends Array<usageStatu>[...]` while for the other one it's - most likely due to the different generation of the plural due to the underscore - reffering to the non arrayed class.

![2024-03-18 at 08 03 25](https://github.com/cap-js/cds-typer/assets/50519619/22366cfa-d164-4e00-b04b-1d214f6614c4)

Without yet being deep in the code I noticed the following differences:

Within the [resolver](https://github.com/cap-js/cds-typer/blob/ee90ea53c1cb6163c2c7a755134a19a9b70a8572/lib/components/resolver.js#L288-L311) the properties are resolved like this:

|Property Name|Singular|Plural|Type Name|
|---|---|---|---|
|usageStatus|usageStatu|UserInterfaces.usageStatus|__.Composition.of.many<UserInterfaces.usageStatus>
|intentMapping|intentMapping|UserInterfaces.intentMapping|__.Composition.of.many<UserInterfaces.intentMapping>

While then in the [visitor](https://github.com/cap-js/cds-typer/blob/ee90ea53c1cb6163c2c7a755134a19a9b70a8572/lib/visitor.js#L312C24-L312C37) the following is derived:

|Property Name|Singular|Plural|Buffer Add String|
|---|---|---|---|
|usageStatus|usageStatu|usageStatus|export class usageStatus extends Array<usageStatu> {}
|intentMapping|intentMapping|intentMapping_|export class intentMapping_ extends Array<intentMapping> {}

I assume the underlying source of the issue is that both are deriving the plural naming in a different fashion and in the visitor it adds the underscore to differentiate while that's missed in the resolver when creating the composition.

- ! Careful, these are just unverified assumptions on my side.

### Environment

```markdown
- **OS**: MacOS
- **Node**: v20.11.0  
- **npm**: 10.5.0
- **cds-typer**: 0.18.1
- **cds**: 7.7.2
```

**Comment by daogrady** [comment]
Hi Tobias,

sorry for the delay. I started looking into it and I'm having trouble making sense of your description. Could you please include a self-contained minimal example where I can observe the described effect? Thanks!

Best,
Daniel

**Comment by tsteckenborn** [comment]
This error doesn't seem to appear anymore in `0.20.1`. Yet a few new ones appeared when updating. Will post them in separate ones.
