### ISSUE TITLE
[BUG] Error when generating TS types for Auxiliary type in CDS

### ISSUE THREAD

**Issue by gaurav-kumar04** [cap-js/cds-typer#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When a custom type in CDS is created by referring to an entity(also called auxiliary type) then the cds-typer fails to generate a valid TS type.
Custom type example:

```cds
entity Airlines {
    key AirlineID : String(3);
        Name      : String(40);
}

type AirlineType : Airlines {} // Auxiliary type;
```
Auxiliary type details: https://cap.cloud.sap/docs/cds/compiler-v2#_2-only-entities-from-same-service-allowed

Generated TS type
```js
export function _AirlineAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Airline extends Base {
        AirlineID?: string;
        Name?: string | null;
      static actions: {
      }
  };
}
export class Airline extends _AirlineAspect(__.Entity) {}
Object.defineProperty(Airline, 'name', { value: 'Airlines' })
export class Airlines extends Array<Airline> {}
Object.defineProperty(Airlines, 'name', { value: 'Airlines' })

export function _AirlineTypeAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class AirlineType extends Base {
      static actions: {
      }
  };
}

/* ERROR: Cannot find name '_AirlinesAspect'. Did you mean '_AirlineAspect' */
export class AirlineType extends _AirlinesAspect(_AirlineTypeAspect(__.Entity)) {}  // <--- Error
Object.defineProperty(AirlineType, 'name', { value: 'AirlineType' })
```

### Expected Behavior

Generated type should be:

```js
export function _AirlineAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Airline extends Base {
        AirlineID?: string;
        Name?: string | null;
      static actions: {
      }
  };
}
export class Airline extends _AirlineAspect(__.Entity) {}
Object.defineProperty(Airline, 'name', { value: 'Airlines' })
export class Airlines extends Array<Airline> {}
Object.defineProperty(Airlines, 'name', { value: 'Airlines' })

export function _AirlineTypeAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class AirlineType extends Base {
      static actions: {
      }
  };
}

/* It should refer to `_AirlineAspect` instead of `_AirlinesAspect`  */
export class AirlineType extends _AirlineAspect(_AirlineTypeAspect(__.Entity)) {} 
Object.defineProperty(AirlineType, 'name', { value: 'AirlineType' })
```

### Steps To Reproduce

1. Setup a TS project with cds-typer enabled
2. Create a `.cds` file
3.  Add the following code:
```cds
entity Airlines {
    key AirlineID : String(3);
        Name      : String(40);
}

type AirlineType : Airlines {} // Auxiliary type;
```
4. Execute the command `tsc --noEmit`, it will show the error in the generated file.

### Environment

```markdown
- **OS** : MacOS
- **Node** : 18.18.0
- **npm** : 9.8.0
- **cds-typer** : 0.18.2 
- **cds** : 7.8.0
```

**Comment by gaurav-kumar04** [comment]
Commenting on this issue to keep it open.

**Comment by daogrady** [comment]
Hi @gaurav-kumar04 ,

sorry for the delayed response. I just checked your initial post and your expected and actual generated code appear to be an empty diff. Running `tsc` against the generated files also shows no error, but maybe this issue has resolved itself in the meanwhile? Could you please check if the original issue persists and let me know with an updated minimal sample? Thanks!

Best,
Daniel

**Comment by gaurav-kumar04** [comment]
Hi @daogrady Yeah I noticed I pasted the same code in both the blocks. I have updated it. But I am not seeing this issue now, may be it got fixed in the later versions? Anyways, I will close this issue since its working fine now.
