### ISSUE TITLE
[BUG] Invalid code generation when extending imported enum

### ISSUE THREAD

**Issue by aschmidt93** [cap-js/cds-typer#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

JavaScript, TypeScript

### Current Behavior

When defining an enum (e.g. in a service) that extends another imported enum (e.g. from schema.cds), the generation will produce invalid code.

![image](https://github.com/cap-js/cds-typer/assets/139967229/b79e086d-fcb5-4d7a-8c06-1828099b7e99)

### Expected Behavior

```ts
export const EnumExample = {
  ONE: "ONE",
  TWO: "TWO",
} as const;
export type EnumExample = "ONE" | "TWO"
```

### Steps To Reproduce

```cds
// schema.cds
namespace de.example;

type EnumExample : String enum {
  ONE = 'ONE';
  TWO;
}
```

```cds
// ExampleService.cds
using {de.example as schema} from '../db/schema';

service ExampleService {
  define type EnumExample : schema.EnumExample;

  action test(val : EnumExample) returns String;
}
```

### Environment

```markdown
- **OS**: Win11
- **Node**: 18.16.1
- **npm**: 9.7.1
- **cds-typer**: 0.19.0
- **cds**: 7.8.0
```

### Anything else?

Related to #169

**Comment by daogrady** [comment]
Hi @aschmidt93 ,

thanks for reporting this issue! I have prepared [a fix](https://github.com/cap-js/cds-typer/pull/197) for this. If you would like, you can [confirm](https://github.com/cap-js/cds-typer/wiki/Trying-Out-Prerelease-Versions) that the fix works with your actual model before I merge it.

Best,
Daniel

**Comment by aschmidt93** [comment]
Hi Daniel,

the fix works, thank you.
