### ISSUE TITLE
CDS Types containing another type, using a one to many relation, results into an incomplete type definition

### ISSUE THREAD

**Issue by p36daniel** [cap-js/cds-typer#20]
Hi, 

the following CDS generates a incomplete result: 

```
type A {
    b                   : B;
    bs                  : many B;
}

type B {
    prop1               : String;
    prop2               : String;
}
```

=> 

```ts
// This is an automatically generated file. Please do not change its contents manually!
export type A = {
    b ?: B;
    bs ?: Array<{}>; //ISSUE
};
export type B = {
    prop1 ?: string;
    prop2 ?: string;
};
```
I would expect the following 

```ts
export type A = {
    b ?: B;
    bs ?: Array<B>; //EXPECTED
};
export type B = {
    prop1 ?: string;
    prop2 ?: string;
};
```

Best regards
Daniel

**Comment by daogrady** [comment]
Hi Daniel,

`array of` (and variations therefore) are still a bit of a gap in cds-typer.
If it that is working for you, you could convert it to `: Composition of many B;` or `: Association to many B;` as a bandaid solution, which should be fully working as of today.

We will make sure to bring full support to the `array of` syntax to cds-typer asap.

Best regards,
also Daniel
