### ISSUE TITLE
[BUG] Inheritance not working for entities

### ISSUE THREAD

**Issue by aschmidt93** [cap-js/cds-typer#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When an entity extends another entity, the generated file references a non-existing aspect and thus contain TS errors.

![image](https://github.com/cap-js/cds-typer/assets/139967229/9fd639c7-33e9-44ca-87b3-c43d1d0fb504)

Related to #149 

### Steps To Reproduce

```cds
entity Orders {
  id   : UUID;
  name : String;
}

entity FinishedOrders : Orders {
  foo : String;
}
```

### Environment

```markdown
- **cds-typer**: 0.19.0
- **cds**: 7.8.0
```

**Comment by daogrady** [comment]
Hi @aschmidt93 ,

thanks for reporting this issue! This is a critical problem and I will address it asap.

Best,
Daniel
