### ISSUE TITLE
[FEATURE] Make types mapping (CDS -> JS) configurable

### ISSUE THREAD

**Issue by mcastrup** [cap-js/cds-typer#209]
### Description

This feature request is related to my previous question https://github.com/cap-js/cds-typer/issues/157.
Currently, you have a hard-coded list, how CDS types are mapped to Javascript/Typescript types, i.e., your [Builtins object](https://github.com/cap-js/cds-typer/blob/main/lib/components/resolver.js#L45):
```js
const Builtins = {
    UUID: 'string',
    String: 'string',
    Binary: 'string',
    LargeString: 'string',
    LargeBinary: 'Buffer | string | {value: import("stream").Readable, $mediaContentType: string, $mediaContentDispositionFilename?: string, $mediaContentDispositionType?: string}',
    Vector: 'string',
    Integer: 'number',
    UInt8: 'number',
    Int16: 'number',
    Int32: 'number',
    Int64: 'number',
    Integer64: 'number',
    Decimal: 'number',
    DecimalFloat: 'number',
    Float: 'number',
    Double: 'number',
    Boolean: 'boolean',
    // note: the date-related types are strings on purpose, which reflects their runtime behaviour
    Date: '__.CdsDate',  // yyyy-mm-dd
    DateTime: '__.CdsDateTime', // yyyy-mm-dd + time + TZ (precision: seconds)
    Time: '__.CdsTime',  // hh:mm:ss
    Timestamp: '__.CdsTimestamp', // yyy-mm-dd + time + TZ (ms precision)
    //
    Composition: 'Array',
    Association: 'Array'
}
```
Even more critical than the mapping of Date to string, which I mentioned in my previous question, is the mapping of Decimal to number. 
We cannot use the 'number' type in our Typescript [application](https://github.tools.sap/erp4sme/crypto-for-business), because we really have to deal with a high precision. The Javascript/Typescript number object does not have a sufficient precision. Thus, we use 'Big' from the [Big.js](https://mikemcl.github.io/big.js/) module, whenever we have to perform calculations, or we just use 'string' to represent a number.

### Suggested Solution

It would be great if the mapping can be configurable, so that the application can decide, which CDS types are mapped to which JS types.
We can also schedule a meeting to discuss our requirements and possible solutions in more detail.

Best regards,
Michael

**Comment by daogrady** [comment]
Hi Michael,

thanks for this suggestion! I am not sure I fully understand the idea though.
The types emitted by cds-typer have no bearing on what types CDS actually uses during runtime. How do you contrive that CDS uses the `Big`-types as part of its `cds.entities`?

Best,
Daniel

**Comment by mcastrup** [comment]
Hello Daniel,

let's have a look at a simplified example. Suppose, we have a CDS entity like
```
entity Foo : {
  amount: Decimal;
}
```
with an amount field of type 'Decimal', which is intended here.

Your cds-typer then generates something like
```js
export function _FooAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Foo extends Base {
        amount?: number | null;
      static actions: {
      }
  };
}
```
When we now use the generated class for typing our property in the Typescript code, it has of course the type 'number':
```js
import type { Foo} from "#cds-models/...";
const foo : Foo = { amount : 1.234567890123456789 }
```

However, as I mentioned above, we will lose precision, when using a 'number' type. We need the 'amount' field to be typed as Big or string in Typescript. 
Thus, we would like to have something like:
```js
export function _FooAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Foo extends Base {
        amount?: Big | string | null;
      static actions: {
      }
  };
}
```

I hope that makes it clearer. :-)

**Comment by daogrady** [comment]
Thanks for attaching the sample. If I understand you correctly, you'd like cds-typer to generate:

```ts
export function _FooAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Foo extends Base {
        amount?: BigInt | null;
      static actions: {
      }
  };
}
```
instead?

**Comment by daogrady** [comment]
Thanks for adding the sample!
I believe there is a misunderstanding in what cds-typer provides you with. Changing the output of `number` to `Big` in cds-typer will not change the fact that the cds _runtime_ will use a `number` for everything that is typed as `Decimal` in your model. It sounds like this is a feature request you might want to direct at the runtime. If the runtime is able to support something like `Big`, cds-typer would follow suite and generate the appropriate types.

**Comment by mcastrup** [comment]
Hello Daniel,

please note that I'm talking about the Typescript files in our application and the runtime on node.js.
I'm not talking about how the CDS or CAP runtime handles CDS Decimal types.
In fact, an amount field, which is typed as Decimal in a CDS View, has at runtime the type 'string' in the request.data object, which is handed over from the Fiori Elements UI to the backend in the request. When we want to assign such an amount field (which has the static type 'any' in the request) to a typed variable, we want to use 'string' or 'Big' here, but not 'number'. So, we cannot use the generated type from your cds-typer module to type our data structure.

Best regards,
Michael

**Comment by daogrady** [comment]
Hi Michael,

> an amount field, which is typed as Decimal in a CDS View, has at runtime the type 'string' in the request.data object

maybe I am misunderstanding your scenario, but I just tried 

```cds
entity Books {
  key ID : Integer;
  title  : String;
  stock  : Decimal;
}
```
with
```csv
ID;title;stock
1;Wuthering Heights;100.12312312312312313123123123
2;Jane Eyre;500.123
```

and at least there I am seeing

![Screenshot 2024-04-18 at 15 39 26](https://github.com/cap-js/cds-typer/assets/103028279/71cc52af-d35e-44d9-9ab8-756328fd47e7)

which suggests to me that CDS' `Decimal` is represented by a `number` in the CDS Node runtime. 
The types generated by cds-typer are supposed to reflect the runtime behaviour and describe the entities you would get from `cds.entities(...)`. 

If you want to convert a property in one of your handlers, then you have to do that manually and that warrants a new (custom defined) type. Maybe you want to extend the existing type generated by cds-typer?

```cds
// model.cds
entity Books {
  title: String;
  stock: String;  // string, to make sure precision is not lost
}
```

```ts
// generated by cds-typer
declare class Book {
  title?: string | undefined
  stock?: string | undefined
}

// declared by you
declare class BetterBook extends Book {
    convertedStock: Big

    constructor (original: Book) {
        super()
        this.title = original.title
        this.stock = original.stock
        this.convertedStock = // your conversion logic to go from string to Big here
    }
}
```

```ts
// service.ts
on('READ', Books, req => {
  // you still receive Books the way the runtime treats them...
  const betterBook = new BetterBook(req.data[0])
  // ...but you can wrap them in your own type where you have fancy data types and use them
})
```

Is this the solution you are looking for?

Best,
Daniel

**Comment by daogrady** [comment]
@mcastrup I hope the proposed solution resolves the issue. If not, feel free to just schedule a quick meeting with me so we can go over the details. 🙂

**Comment by daogrady** [comment]
Hi @sjvans,

numerics are currently all represented as `number`. If the runtime supports both, I can change the emitted type to `number | string`. Can you describe in which cases a numeric is represented as number or string?

Best,
Daniel

**Comment by sjvans** [comment]
hi @daogrady 

the client actually chooses. see [Controlling the Representation of Numbers](https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_ControllingtheRepresentationofNumber). the runtime will take as provided. from db, it will always be selected as a string (cf. https://github.com/cap-js/cds-dbs/pull/616). with legacy db and protocol adapters it's a bit messy, but we're in the process of cleaning that up. ;)

best,
sebastian

**Comment by mcastrup** [comment]
Hi @daogrady

according to Sebastian's comment
> decimals and int64 can be numbers or strings at runtime.  

will you then change the emitted type to `number | string` ?

Best regards,
Michael

**Comment by daogrady** [comment]
Hi @mcastrup,

I can not change it on short notice, as this will be a breaking change for everyone expecting `number` for their numeric fields, but I will bring this up in my next meeting with the project's PO (next week) to see what we can do to accommodate all possible use cases for our users while hopefully not breaking too much existing code.

Best,
Daniel

**Comment by daogrady** [comment]
Hi @mcastrup ,

we discussed the matter and since the runtime itself is currently in the process of cleaning things up around numerics, we'd like to opt for a quickfix.
We could introduce a switch to cds-typer, something like `--IEEE754Compatible`, that emits _all_ `Cds.Decimal`et al. types as `string | number`. This would be a bandaid solution and would be phased out once we have a more stable approach.
Would this fix your issue at hand?

Best,
Daniel

**Comment by mcastrup** [comment]
Hi @daogrady ,

thanks for the information. This sounds good and fulfils our requirements. :-)
Please, let me know, once the solution is available.

Best regards,
Michael
