### ISSUE TITLE
[QUESTION] Release 0.20

### ISSUE THREAD

**Issue by aschmidt93** [cap-js/cds-typer#211]
### Question

Hi there,

when will version 0.20.0 be released? We're looking forward to it :)

**Comment by daogrady** [comment]
Hi @aschmidt93,

sorry for the wait! I had originally planned to release it last week, but then I stumbled upon a huge breaking change that came with some of the features introduced in 0.20. So I am currently scrambling to get those fixed to reduce the number of regressions.
I will release it asap, hopefully by the latest of tomorrow, if I can.

Best,
Daniel

**Comment by daogrady** [comment]
PSA: 0.20.0 is out now
