### ISSUE TITLE
[BUG] Build failes for operations without return type

### ISSUE THREAD

**Issue by chuckberrry** [cap-js/cds-typer#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

JavaScript, TypeScript

### Current Behavior

Version 0.20.0 adds additional logic for actions and functions (operations).

In cds services it is allowed by the compiler to omit a return type, e.g.
```cds
action actionName(input: String);
```

In cds-typer function "lib/visitor.js" you can find the following logic:
```js
 #printOperation(name, operation, kind) {
        // FIXME: mostly duplicate of printAction -> reuse
        this.logger.debug(`Printing operation ${name}:\n${JSON.stringify(operation, null, 2)}`)
        const ns = this.resolver.resolveNamespace(name.split('.'))
        const file = this.fileRepository.getNamespaceFile(ns)
        const params = this.#stringifyFunctionParams(operation.params, file)
        const returnType = this.resolver.resolveAndRequire(operation.returns, file)
        const returns = this.inlineDeclarationResolver.getPropertyDatatype(
            returnType,
            returnType.typeInfo.isArray ? returnType.typeName : returnType.typeInfo.inflection.singular
        )
        file.addOperation(name.split('.').at(-1), params, returns, kind)
    }
```
As you can see the function `this.resolver.resolveAndRequire(operation.returns, file)` is called with the property `operation.returns`.
In the mentioned action example from above, the `operation.returns` is `undefined`.
This leads to the following error while trying to create cds-types:

node_modules/@cap-js/cds-typer/lib/components/resolver.js:438
        const target = element.target?.name ?? element.type?.ref?.join('.') ?? element.type
TypeError: Cannot read properties of undefined (reading 'target')
    at Resolver.resolveAndRequire 

As the action definition in cds is valid, I consider this a bug.

best regards,
Armin

### Expected Behavior

No error

### Steps To Reproduce

use the following action:
```cds
action actionName(input: String);
```

### Environment

```markdown
- **OS**: MacOS
- **Node**: 18.18.0
- **npm**: 9.8.1
- **cds-typer**: 0.20.0
- **cds**: 7.8.1
```

**Comment by daogrady** [comment]
Hi @chuckberrry ,

thanks for bringing this to my attention and for the thorough analysis. I overlooked `void` actions and will release a patch for this today.

Best,
Daniel
