### ISSUE TITLE
[FEATURE] Add _kind property to entities/types

### ISSUE THREAD

**Issue by aschmidt93** [cap-js/cds-typer#221]
### Description

Currently, there's no way to distinguish between entities and types in the generated files.

### Suggested Solution

Add a `_kind` property to entities and types as done for actions/functions in #200

**Comment by daogrady** [comment]
Hi Andreas,

thanks for this suggestion. While I am not opposed, would you mind showing a use case where you need this `kind` property to be present to distinguish between types and entities?

Best,
Daniel

**Comment by daogrady** [comment]
Hi @aschmidt93,

I just looked into it and I'm afraid the best I can currently offer you is something that looks a bit like this:

```ts
class MyType {
  static readonly kind: 'type' | 'entity' | 'aspect' = 'type'
}

class MyAspect {
  static readonly kind: 'type' | 'entity' | 'aspect' = 'aspect'
}

class MyEntity {
  static readonly kind: 'type' | 'entity' | 'aspect' = 'entity'
}
```

so the type remains a bit vague. The reason for this is that types, entities, and aspects can extend one another:

```ts
class MyType {
  static readonly kind = 'type'  // implicitly also strictly typed as 'type'
}

class MyAspect extends MyType {
  static readonly kind = 'aspect'  // wants to strictly type as 'aspect', which clashes with the inherited declaration
}
```

will this still be useful to you?

Best,
Daniel

**Comment by daogrady** [comment]
@aschmidt93 ping to see if this is still relevant to you 🙂

**Comment by aschmidt93** [comment]
Thank you, I'll try that.

**Comment by aschmidt93** [comment]
The solution works for me :)
