### ISSUE TITLE
[FEATURE] Export const of type alias

### ISSUE THREAD

**Issue by aschmidt93** [cap-js/cds-typer#222]
### Description

When importing an enum from another .cds file, the generated file only exports the type alias but not the const variable.
Also see #194 

v0.20.1

```cds
// schema.cds
type MyEnum : String enum {
  Foo;
  Bar;
}
```

```cds
// service.cds
type MyEnum   :  schema.MyEnum;
```

```ts
// service index.ts
export type MyEnum = _de_example.MyEnum;
```

### Suggested Solution

Export the const, too.

**Comment by daogrady** [comment]
Hi @aschmidt93 ,

I have prepared [a PR](https://github.com/cap-js/cds-typer/pull/263) to introduce this feature. Would you like to check it out before the merge?

Best,
Daniel

**Comment by aschmidt93** [comment]
Hi @daogrady,

thank you it works as intended.
