### ISSUE TITLE
[BUG] cds build plugin code is missing in npm package

### ISSUE THREAD

**Issue by Kyrodan** [cap-js/cds-typer#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

JavaScript, TypeScript

### Current Behavior

Running `cds build --for typescript`results in 
```
[ERROR] No provider found for build task 'typescript'. Ensure that all required dependencies have been added and 'npm install' has been executed.
```

### Expected Behavior

cds-typer typescript plugin should be found and be executable.

### Environment

```markdown
- **OS**: Windows 10
- **Node**: v20.13.1
- **npm**: 10.8.0
- **cds-typer**: 0.21.0
- **cds**: 7.9.1
```

### Anything else?

It seems that `cds-plugin.js` is missing in npm package:
![grafik](https://github.com/cap-js/cds-typer/assets/355178/f78d5441-46c4-41fe-a43c-35ceb4414460)

**Comment by daogrady** [comment]
Hi Daniel,

great catch! I will release a patch for this asap.

Best,
Daniel
