### ISSUE TITLE
[QUESTION] Correct usage of Entity Types for handler method

### ISSUE THREAD

**Issue by Kyrodan** [cap-js/cds-typer#252]
### Question

Im using TypeScript with cds-types like mentioned in latest CAPire.
In https://cap.cloud.sap/docs/tools/cds-typer#cds-typer-vscode the sample states the usage of Entities as follows:

```
const { Books } = require('#cds-models/bookshop')
service.before('CREATE', Books, ({ data }) => { /* data is of type Books */})
```

If I now transpile this code using _tsc_ for production (not using ts-node) the result is:
```
const bookshop_1 = require("#cds-models/bookshop");
service.on("CREATE", bookshop_1.Books, ({ data }) => { /* data is of type Books */})
```

This looks okay, **BUT**:
My Service does not run correctly, a message appears if I call the CREATE handler:
```Service "bookshop" has no handler for "CREATE bookshop.Books".```
The TS-Code using ts-node works as expected.

If I now replace `Books` with `Books.name` in TypeScript example above, then the compiled JS-Code works as expected in both environments.

Is this a bug or a incorrect documentation?
What is the preferred way to use the Books entity type in this sample?

**Comment by daogrady** [comment]
Hi Daniel,

it reads as if you are running into the (known) problem that the transpiler also touches the types generated by `cds-typer`, which messes with the runtime behaviour.
Have you also followed [this](https://cap.cloud.sap/docs/tools/cds-typer#integrate-into-typescript-projects) part of the documentation that explains the use of `tsc` in combination with `cds-typer`?

Best,
Daniel

**Comment by Kyrodan** [comment]
Hi Daniel,
that's it. Thanks for pointing me to this. 
Regards,
Daniel
