### ISSUE TITLE
[BUG] Multi-level aspect inheritance not supported

### ISSUE THREAD

**Issue by rasmk** [cap-js/cds-typer#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

I have an entity that inherits from 2-level aspect hierarchy:

```cds
aspect Aspect1 {
  property1 : String(10) not null;
}

aspect Aspect2: Aspect1 {
  property2 : String(20) not null;
}

entity MyEntity : Aspect2 {
    key ID : UUID not null;
}
```

This generates class `MyEntity` that has properties `ID` and `property2`, but it does not have property `property1`.

From the source it is clear why: class `MyEntity` inherits from `_MyEntityAspect` (which has `ID`) and from `_Aspect2Aspect` (which has `property2`).
`_Aspect1Aspect` is not in the inheritance hierarchy. Neither `MyEntity`, nor `_MyEntityAspect`, nor `_Aspect2Aspect` inherit from it.
There is `Aspect2Entity` that inherits from `_Aspect1Aspect`. But it does not belong to the hierarchy either.

### Expected Behavior

Properties from all aspects in the CDS inheritance hierarchy should be present in the class generated for the entity.

I suppose it should be the generated aspects that inherit from the parent aspects, not the entities.

### Steps To Reproduce

See aspect/entity inheritance hierarchy in _current behavior_.

### Environment

```markdown
- **OS**: macOS 14.5
- **Node**: v18.20.1
- **npm**: 10.5.0
- **cds-typer**: 0.21.2
- **cds**: 7.8.0
```

**Comment by WAVIFICATION** [comment]
Having the same issue on 0.21.2 and 0.22.0(latest version as of this writing).

**Comment by daogrady** [comment]
Hi @rasmk, hi @WAVIFICATION ,

thanks for bringing this to our attention. Now that I'm seeing it, I am actually surprised that you're the first ones that run into this issue. 🙂
I have prepared [a fix](https://github.com/cap-js/cds-typer/pull/267). Feel free to try it out before I merge it.

Best,
Daniel
