### ISSUE TITLE
[BUG] Almost every entity is marked as singular for external cds service

### ISSUE THREAD

**Issue by tihollinger** [cap-js/cds-typer#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

JavaScript

### Current Behavior

After update to the v0.21.2, almost every entity of our external service is marked as is_singular. Like this: 
![image](https://github.com/cap-js/cds-typer/assets/156799574/eab95d2d-6b26-4a62-b659-7994c588e54d)

### Expected Behavior

For example, entity **Studies** should not be marked as is_singular. 

### Environment

```markdown
| @cap-js/audit-logging  | 0.8.0                                                 |
| @cap-js/cds-typer      | 0.21.2                                                |
| @cap-js/cds-types      | 0.2.0                                                 |
| @cap-js/sqlite         | 1.7.1                                                 |
| @sap/cds               | 7.9.2                                                 |
| @sap/cds-compiler      | 4.6.2                                                 |
| @sap/cds-dk            | 7.9.3                                                 |
| @sap/cds-dk (global)   | 7.9.3                                                 |
| @sap/cds-fiori         | 1.2.4                                                 |
| @sap/cds-foss          | 5.0.0                                                 |
| @sap/cds-hana          | 2.0.0                                                 |
| @sap/cds-indexer       | 1.0.14                                                |
| @sap/cds-mtxs          | 1.18.1                                                |
| @sap/cds-shim          | 0.5.45                                                |
| @sap/eslint-plugin-cds | 3.0.3                                                 |
| Node.js                | v18.14.1                                              |
```

**Comment by daogrady** [comment]
Hi @tihollinger ,

good catch, thanks for reporting this issue!
I have prepared [a fix](https://github.com/cap-js/cds-typer/pull/264) for this. Would you like to give it a whirl on your model before I merge it?

Best,
Daniel

**Comment by tihollinger** [comment]
Hi @daogrady ,

thanks for the quick fix! I tried it with my model and it works like a charm! 

Best,
Tim

**Comment by daogrady** [comment]
Hi Tim,

thanks for the confirmation, glad it works for you!

Best,
Daniel
