### ISSUE TITLE
[QUESTION] What needs to be configured to make dynamic import work in monorepo approach?

### ISSUE THREAD

**Issue by tiosteel** [cap-js/cds-typer#271]
### Question

Good day colleagues,

I started to setup my first CAP-TS project in a mono-repository approach.
I have a service into one of the workspaces. Also my database is in a workspace.

Locally I want to launch everything at once with a single command from root.
So in tsconfig.json I have
```
      ...
       "rootDirs": [
            "./srv",
            "./@cds-models"
        ],
        "paths": {
            "#cds-models/*": [
                "./@cds-models/*/index.ts"
            ]
        }
    },
    "include": [
        "./srv/**/*",
        "./database/**/*"
    ]
``` 

the @cds-models is generated fine with console command `npx @cap-js/cds-typer '*' --outputDirectory @cds-models`
_somehow there's no respective options in my VSCode extension settings - maybe because it's Mac_

the service (srv/calculator/srv/calculator.ts) code is:
```
import { ApplicationService } from "@sap/cds";
import type { EuriborValue } from '#cds-models/mortgagecalc/db/tables';
import type { euriborPeriod } from '#cds-models/mortgagecalc/db/types';

export class CalculatorService extends ApplicationService {

    async init(): Promise<void> {
        return super.init();
    }
    
    async getEuribor(day: Date, period: euriborPeriod): Promise<number|undefined> {
        const { EuriborValues } = await import('#cds-models/mortgagecalc/db/tables');
        const result: EuriborValue|undefined = await SELECT.one.from(EuriborValues).where({day: {'<=': day}});
        
        return result?.[period];
    }
}
```

lines 2-3 are working fine, but on the async import on 12 `const { EuriborValues } = await import('#cds-models/mortgagecalc/db/tables');` I face next error (can be reproduce if run request in test/http/calculator.http)

![image](https://github.com/cap-js/cds-typer/assets/3261724/5df1c6ec-0620-4d88-9667-0fcc808fb326)

Any idea what should I do in order to fix this?
My repository is https://github.com/tiosteel/mortgagecalc

Thank you in advance.
Best regards, Mikhail.

**Comment by daogrady** [comment]
Hi Mikhail,

thanks for approaching us with this issue.

> somehow there's no respective options in my VSCode extension settings - maybe because it's Mac

That is weird. I am on a Mac myself and I do see the settings in vscode.
![Screenshot 2024-07-04 at 15 53 35](https://github.com/cap-js/cds-typer/assets/103028279/30aae84e-16a4-4258-a451-cf2d983ee81c)
Does generating the type definitions when saving a .cds-File work? Is there any output in the CDS channel?
![Screenshot 2024-07-04 at 15 54 43](https://github.com/cap-js/cds-typer/assets/103028279/1e47ba50-ead7-4213-b9f7-b5a07df540f6)
There may be a general setup problem with the extension.


Regarding the actual question: could you please also add the command you are using to start the server?

Best,
Daniel

**Comment by tiosteel** [comment]
Hi Daniel, thanks for a quick respond!

> Regarding the actual question: could you please also add the command you are using to start the server?

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "cds-ts serve",
      "command": "npx cds-ts serve",
      "request": "launch",
      "type": "node-terminal"
    }
  ]
}
```

![image](https://github.com/cap-js/cds-typer/assets/3261724/c68cdda2-1c9c-400c-a128-6f2d8933a80f)

> That is weird. I am on a Mac myself and I do see the settings in vscode.

Regarding extension - I have just this:
![image](https://github.com/cap-js/cds-typer/assets/3261724/6c088e61-5744-44e4-bf5f-3577aa45cc5e)
extension version: v6.3.0
VSCode version: 1.70.0

**Comment by hakimio** [comment]
Why do you need to set `tsconfig` path for `cds-models` when using workspaces? Just add a new workspace package with separate `package.json` for your `cds-models`, sth like `@my-org/cds-models` and it should just work since the models package will be symlinked to your `node_modules`.
