### ISSUE TITLE
[BUG] TypeScript `cds build` task unwantedly deletes files from custom build steps

### ISSUE THREAD

**Issue by rasmk** [cap-js/cds-typer#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

After I have installed the cds-typer in my MTA project, the .mtar file generated by `mbt build` is corrupted.
More precisely, all TypeScript/JavaScript files in my _gen/srv_ folder get removed.

### Expected Behavior

I expect cds-typer should not touch files it does not own.

In fact, I would be better off if cds-typer would not do anything during build process and I could handle the build stuff myself.

### Environment

```markdown
- **OS**:
- **Node**:
- **npm**:
- **cds-typer**: 0.24.0
- **cds**: 8.0.4
```

### Anything else?

The problem is caused by this code in _cds-plugin.js_ file:

```JavaScript
// remove the js files generated by the nodejs buildtask,
// leaving only json, cds, and other static files
await rmFiles(this.task.dest, ['.js', '.ts'])
```

I commented the `rmFiles` line out and my mtar works again.

**Comment by daogrady** [comment]
Hi Rafal,

thanks for the report and sorry for the inconvenience! 
Do you see any output from your `cds build` command?

Best,
Daniel

**Comment by rasmk** [comment]
Hello Daniel,
no, there is nothing of interest in the log.

Additional info:
As, to my understanding, the .js files being generated by cds-typer need to be included in the mtar, I run cds-typer with `--outputDirectory srv/generated/cds-models`. This way it becomes a part of the _srv_ folder and is auto-propagated to _gen_ folder during build and lands in the generated mtar without any extra effort.

Then I set up paths in my _tsconfig.json_ as follows:

```json
    "paths": {
      "#cds-models": ["./srv/generated/cds-models/com/pacg/cssp/index.ts"],
      "#cds-models/*": ["./srv/generated/cds-models/*/index.ts"]
    }
```

This makes the namespaced model (db artifacts) proposed before any artifacts from service .cds files in the code completion.

I have the _tsconfig.cdsbuild.json_ (found with debugger) file. It loosens the compiler rules, but only for the prod build. In dev I want to keep strict. I had to add it due to #273.

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "strict": false,
    "useDefineForClassFields": false
  }
}
```

I spent quite some time in debugging. Trying to understand what was going on. If you have any specific question, I may be able to answer.

My general thought is, the plugin is trying to do too much. Removing the files, executing `tsc` - it is not its responsibility, is it? I run `tsc` myself in mta->before_all. No need to repeat it.

I believe, the content generated by cds-typer should be brought to gen and no other activities should be done by the cds plugin. If you want to ensure they are clean, you can run cds-typer with certain output (but you need then take care for cases like mine, where the output is already there). Or just copy the files. Or (my favourite) do nothing. And let the users know, they need to take care the files are included in the generated runtime code.

Best regards
Rafał

**Comment by daogrady** [comment]
Hi Rafal,

thanks for the additional information you have provided. I do agree in parts that it would be preferable for the build task to not touch files created by other tasks. But I am afraid in this case it was a necessity, due to how the files generated by cds-typer work.
Your setup looks a bit excessive on first glance. You should not need to manually call `tsc` as part of the build process, as the build plugin provided by cds-typer would do that for you. But maybe this can actually be fully circumvented: I am currently working on [providing a fix](https://github.com/cap-js/cds-typer/issues/274#issuecomment-2255699361) for the problem you mentioned. Would being able to use the strict config in prod unblock you?

Best,
Daniel

**Comment by rasmk** [comment]
@daogrady thanks for taking my issue with priority 🙂

I think my setup is right. It should not be cds-typer to compile my TypeScript project. It is an opt-in plugin. And I see its responsiblity as: _generating TS/JS type definitions from CDS artifacts_. If it is such, it should not try to be a general purpose TS tool for cap projects.

Our project is over a year old. We use _cds2types_ in it. And while cds-typer is not a part of it, we do run `tsc` in before_all. And that makes sense to me.

Transition to cds-typer should be a transparent change in my opinion. It should  replace one type generator with another.

And to answer your question: I can use build-only tsconfig as a workaround. Since I already know it, it's ok to live with it. What is blocking me is that I am currently loosing my js files in the _srv_ folder. When this is fixed, I can move on.

**Comment by daogrady** [comment]
Hi Rafal,

I see your point, but we must try to accommodate users of varying degree of commitment and skill level, so we try to not burden users with having to maintain yet another dependency and integrate new features with existing workflows. So cds-typer was a natural fit for providing build support for TS projects. 

> We use cds2types in it. And while cds-typer is not a part of it

So if you are not using cds-typer, I guess you could remove it from your dependencies then? Would that not solve this unwanted behaviour? 🤔

> What is blocking me is that I am currently loosing my js files in the srv folder. 

I am afraid there is always the chance of running into issues with newly added features users were formerly working around when they were missing. May I suggest [setting your build process](https://cap.cloud.sap/docs/guides/deployment/custom-builds#build-task-properties) to keep unwanted plugins from running? In your case, you would specify the build plugins you _want_ to run, forgoing the `typescript` plugin.

Please let me know if this is an option for you.

Best,
Daniel

**Comment by rasmk** [comment]
Hello Daniel,
we are about to switch from cds2types to cds-typer.
cds2types, hard-sets dependency to cap 7. Became a bit hacky to upgrade cap to 8. I have my own clone now.

And we are at the moment in process of refreshing the tools and dependencies to be up to date.

So, not yet using cds-typer, but trying to jump on this train 🙂

> May I suggest [setting your build process](https://cap.cloud.sap/docs/guides/deployment/custom-builds#build-task-properties) to keep unwanted plugins from running? In your case, you would specify the build plugins you want to run, forgoing the typescript plugin.

Do I understand it right that if I explicitly enable some plugins, the plugin autodiscovery will not be applied and only the plugins I specify are executed? That could be an option for me.

Best regards
Rafał

**Comment by daogrady** [comment]
Hi Rafal,

> Do I understand it right that if I explicitly enable some plugins, the plugin autodiscovery will not be applied and only the plugins I specify are executed? That could be an option for me.

Yesn't. To be precise: the plugins will still be discovered, but only the ones you explicitly list will be executed.

Best,
Daniel

**Comment by rasmk** [comment]
Thanks for the hint @daogrady. That solves my problem and I can continue the switch to cds-typer 😎
I leave the issue open, as I assume you need to find a general solution.
