### ISSUE TITLE
[FEATURE] Use `Proxy` to wrap the cds.entities access in the generated index.js files

### ISSUE THREAD

**Issue by stockbal** [cap-js/cds-typer#285]
### Description

Currently the recommendation from CAP https://cap.cloud.sap/docs/tools/cds-typer#subpath-imports is to use dynamic imports to be safe during runtime.
Generally speaking, dynamic imports should only be used if really necessary (e.g. dynamic paths, reduction of loading time because of module size).

### Suggested Solution

To avoid these dynamic imports I propose an adjustment of the `modules.exports` expressions in the index.js files to wrap the `cds.entities` access to `Proxy` objects.

Example of an index.js file after the rework.
![image](https://github.com/user-attachments/assets/969e8eea-5566-4a19-98e1-6d18e28033f4)

The used function `createEntityProxy` will be created in the reuse module `@cds-models/_/index.js` and will perform the actual Proxy creation for the cds entities.

See #281

**Comment by daogrady** [comment]
Fixes as of https://github.com/cap-js/cds-typer/pull/281
