### ISSUE TITLE
[BUG] Blocking issue with builder plugin which causes builds to fail if a sidecar mtx is present

### ISSUE THREAD

**Issue by geert-janklaps** [cap-js/cds-typer#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Hi,

We've just upgraded our existing CAP 7 project to CAP 8, everything seems to be working fine up until the build phase.
Since this is a multitenant project, we have a sidecar in place for which it seems the builder plugin tries to generate types for.

I couldn't seem to find a way to disable the plugin at first sight, so this is currently blocking our build process.

Screenshot:
![Screenshot from 2024-08-07 08-08-20](https://github.com/user-attachments/assets/7de2167f-654a-4948-85a8-99761bbca949)

Cheers,
Geert-Jan

### Expected Behavior

The builder plugin not trying to generate types for the standard SAP packages, but only for custom models.

### Environment

```markdown
| ---------------------- | ------------------------------------------------------ |
| @cap-js/asyncapi       | 1.0.2                                                  |
| @cap-js/cds-typer      | 0.24.0                                                 |
| @cap-js/cds-types      | 0.6.4                                                  |
| @cap-js/hana           | 1.1.1                                                  |
| @cap-js/openapi        | 1.0.4                                                  |
| @cap-js/sqlite         | 1.7.3                                                  |
| @sap/cds               | 8.1.0                                                  |
| @sap/cds-compiler      | 5.1.2                                                  |
| @sap/cds-dk            | 8.1.1                                                  |
| @sap/cds-dk (global)   | 8.1.1                                                  |
| @sap/cds-fiori         | 1.2.7                                                  |
| @sap/cds-foss          | 5.0.1                                                  |
| @sap/cds-mtxs          | 2.0.5                                                  |
| @sap/eslint-plugin-cds | 2.7.0                                                  |
| Node.js                | v20.16.0                                               |
| home                   | /workspaces/ICM-Service-Portal/node_modules/@sap/cds   |
```

**Comment by daogrady** [comment]
Hi Geert-Jan,

sorry for the inconvenience! You can approach this the other way around and instead [explicitly list the plugins that are supposed to run](https://cap.cloud.sap/docs/guides/deployment/custom-builds#build-task-properties).
Does this help?

Best,
Daniel

**Comment by geert-janklaps** [comment]
Hi @daogrady,

Thanks for pointing me in the right direction! I'm trying it out as we speak, will keep you posted!

Cheers,
Geert-Jan

**Comment by geert-janklaps** [comment]
Hi @daogrady,

Disabling the builder plugin did in fact work, keeping the existing script / step in the build process generate the types.

Cheers,
Geert-Jan

**Comment by daogrady** [comment]
Hi Geert-Jan,

glad you were able to find a solution that works for you!
Just so I understand correctly: did you explicitly list the plugins you wanted to run and omitted `typescript` to bypass the faulty generation process?

Best,
Daniel

**Comment by geert-janklaps** [comment]
Hi @daogrady,

I did exactly that, as mentioned in the documentation during the build process the build configuration json is displayed. I copied that over to my package.json & just removed the typescript one.

Cheers,
Geert-Jan

**Comment by daogrady** [comment]
Great! That is actually the preferred way to do it as of today, so I'll consider this issue solved. But as you are not the first person running into this, I will bring up the idea of explicitly disabling plugins instead in the next meeting on the build mechanism. Cheers!

**Comment by YoussefBoudiba** [comment]
Hi, I'm facing the same issue. While the suggested fix (using a custom build and omitting TypeScript) works, I'm wondering if there's a plan to update the source so that this workaround won't be necessary in the future?

**Comment by daogrady** [comment]
Hi Youssef,

yes, the upcoming release [will introduce a configuration option](https://github.com/cap-js/cds-typer/blob/main/CHANGELOG.md#added-1) to do so.

Best,
Daniel
