### ISSUE TITLE
[QUESTION] Monorepo approach - consuming @cds-models from root package

### ISSUE THREAD

**Issue by geert-janklaps** [cap-js/cds-typer#292]
### Question

Hi,

I'm in the process of converting parts of an existing project into some reusable packages, because we're adding additional modules (e.g. API access / Broker) and want to reuse some of the functionality of the existing base application across modules.

I've moved all my code to a new sub-project and adapted the root project to use the logic from the new package, which seems to be working fine as such. Only problem I'm currently running into is that I can't reference the @cds-models with an import in the sub-project. Resulting in following error when running the application:

error TS2307: Cannot find module '#cds-models/API_COMPANYCODE_SRV' or its corresponding type declarations.

I had a look at #271, but this seems to be a different approach compared to what I'm doing (in this example each sub-project has its own @cds-models).

Currently in the subproject I have a very minimal tsconfig referencing the root tsconfig:
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../gen/reuse/sync"
  }
}
```

What's the recommended approach on this one? Any pointers in the right direction are really appreciated.
(I'm assuming I could run multiple cds-typer commands and create the same @cds-models in the sub-projects, but it feels like something I want to avoid)

Cheers,
Geert-Jan

**Comment by daogrady** [comment]
Hi Geert-Jan,

just so I understand correctly, your project layout now looks something like this:

```

monorepo/
├── @cds-models
├── api/
│   ├── package.json
│   └── ...
└── broker/
    ├── package.json
    └── ...
```

And you are trying to include type definitions that are contained within `monorepo/@cds-models` in `monorepo/broker`, is that correct?

Best,
Daniel

**Comment by hakimio** [comment]
You can simply use `npm` or `yarn` workspaces to achieve this. You don't have to modify the `tsconfig` or `package.json` to define the path to your `#cds-models` since the models package will be symlinked to your `node_modules` when using workspaces.
- Specify your `workspaces` directories in the root `package.json`.
- Add `package.json` to your `@my-org/cds-models` library:
```json
{
    "name": "@my-org/cds-models",
    "version": "0.0.0",
    "private": true,
    "exports": {
        ".": {
            "types": "./index.ts",
            "node": "./index.js",
            "import": "./index.js",
            "default": "./index.js"
        },
        "./foo": {
            "node": "./FooService/index.js",
            "import": "./FooService/index.js",
            "default": "./FooService/index.js",
            "types": "./FooService/index.ts"
        },
        "./sap": {
            "node": "./sap/common/index.js",
            "import": "./sap/common/index.js",
            "default": "./sap/common/index.js",
            "types": "./sap/common/index.ts"
        },
        "./cds-types": {
            "node": "./_/index.js",
            "import": "./_/index.js",
            "default": "./_/index.js",
            "types": "./_/index.ts"
        }
    },
    "scripts": {
        "build": "cds-typer ../my-backend/srv/index.cds --outputDirectory ."
    },
    "dependencies": {
        "tslib": "^2.6.3"
    },
    "devDependencies": {
        "@cap-js/cds-typer": "0.22.0",
        "@types/node": "^20.14.14",
        "typescript": "~5.4.5"
    }
}
```
- Add `@my-org/cds-models` as a dependency to one of your monorepo applications:
```json
{
    "name": "@my-org/my-backend",
    "private": true,
    "scripts": {
        "start": "npx cds-ts watch",
        "start:js": "npx cds-serve",
    },
    "engines": {
        "node": "^20.9.0",
        "npm": "^10.0.0"
    },
    "dependencies": {
        "@my-org/cds-models": "workspace:^",
        "@cap-js/postgres": "^1.10.0",
        "@dxfrontier/cds-ts-dispatcher": "^2.1.4",
        "@dxfrontier/cds-ts-repository": "^1.1.3",
        "@sap/cds": "^7.9.4",
        "express": "^4.19.2",
        "tslib": "^2.6.3"
    },
    "devDependencies": {
        "@sap/cds-dk": "^7.9.6",
        "@types/express": "^4.17.21",
        "@types/luxon": "^3.4.2",
        "@types/node": "^20.14.14",
        "ts-node": "^10.9.2",
        "typescript": "~5.4.5"
    }
}
```
- Now you can simply import your models from `@my-org/cds-models` library without any changes to your `tsconfig`:
```ts
import {AfterCreate, EntityHandler, Result} from '@dxfrontier/cds-ts-dispatcher';
import {Customer} from '@my-org/cds-models/foo';

@EntityHandler(Customer)
export class CustomerHandler {

    @AfterCreate()
    async afterCreate(@Result() result: Customer) {
        console.log('After customer create: ', result);
    }

}
```

**Comment by geert-janklaps** [comment]
Hi @hakimio, @daogrady,

Looks exactly what I'm looking for, going to try this out in the next few days. Thank you for the pointer in the right direction, really appreciated!

@daogrady,
Wouldn't this approach be a good thing to include in the types generator as an option? (e.g. automatically creating a package.json exporting the types as described by @hakimio)

Manually maintaining this is doable if you don't have to many models, one of the projects I'm working on already has +20 different models which makes this approach already a little more intensive. 

Cheers,
Geert-Jan

**Comment by daogrady** [comment]
Hi everyone,

that is a valid point. Sadly, I do not have access to user stats where I could assess how many of our users employ a monorepo setup an face these struggles you describe (maybe we need to have the GitHub discussions page to enable voting on features?).
But I will definitely take this into our next planning and bring up the topic of accommodating mono repo setups. Even if we don't add a feature for automatic configuration, this information should be reflected in a knowledge base, probably in CAPire.
Regardless, I will leave this issue open for now until you can confirm the proposed solution solves your problem.

@hakimio thanks for weighing in and suggesting this solution! 👍

Best,
Daniel

**Comment by geert-janklaps** [comment]
Hi @hakimio, @daogrady,

This approach seems to be working perfectly fine! 
Thanks for the pointers in the right direction, greatly appreciated!

@daogrady: when it comes to monorepo's, I think this will be more and more common in the future. For smaller projects the default setup is definitely sufficient, but once you start using multiple modules which consume the same types you'll always end up using mono repo setups since the chances you'll encounter logic which should be used across multiple modules needs to be centralized. (alternative would be to completely decouple the lifecycle and publish such logic to e.g. NPM, but that feels like overkill if the logic is only used within the same project)

If the approach of generating such package.json using the cds-typer ever gets considered, happy to chime in / help on the topic.

Cheers,
Geert-Jan

**Comment by daogrady** [comment]
Hi Geert-Jan,

we discussed this topic internally and would like to get a better understanding of how our users would typically structure their projects where this kind of shared types is required. 
Would you mind sharing your project? If you prefer, you can obviously also do this in private.

Best,
Daniel
