### ISSUE TITLE
[BUG] Erroneous generated entities when overriding properties of parent

### ISSUE THREAD

**Issue by aschmidt93** [cap-js/cds-typer#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When an entity extends another entity and changes the value of a property, the generated typescript code is erroneous. 
Only in versions > 0.22

### Steps To Reproduce

```cds
type OrderState         : String enum {
        Ready    = 'READY';
    };

    type FinishedOrderState : String enum {
        Done     = 'DONE';
        Canceled = 'CANCELED';
    }

    entity Orders {
        key ID          : UUID;
            state       : OrderState;
            predecessor : Association to Orders;
    };

    entity FinishedOrders : Orders {
        state       : FinishedOrderState;
        predecessor : Association to FinishedOrders;
    }
```

Generates 
![image](https://github.com/user-attachments/assets/1d227e45-f588-4728-b101-f56f348dace2)

### Environment

```markdown
- **cds-typer**: >0.22
- **cds**: ^7
```

**Comment by daogrady** [comment]
Hi Andreas,

thanks for reporting this issue!
To be honest, I wouldn't know how a matching type definition would look like and I feel like this should not be allowed in CDS. @johannes-vogel could you please weigh in and let me know if extending and entity and thereby changing the type of a property is desired behaviour?

Minimal example:

```cds
entity A {
  foo: Integer
};

entity B: A {
  foo: String
}
```

Best,
Daniel

**Comment by hakimio** [comment]
Looking just at TypeScript types, the overrides are incompatible. All those cases should result in TS errors.
- `OrderState` is incompatible with `FinishedOrderState`.
- Same goes for `string` and `number` example.

Here is how corrected TS types could look like:
```ts
enum OrderState {
    Ready    = 'READY',
    Done     = 'DONE',
    Canceled = 'CANCELED'
};

interface Order {
        ID          : UUID;
        state       : OrderState;
        predecessor : Order;
};

interface FinishedOrder: Order {
    state       : OrderState.Done | OrderState.Canceled;
    predecessor : FinishedOrder;
}
```

**Comment by daogrady** [comment]
Hi Andreas,

we looked into the issue and I am afraid this is a capability of CDS that is not really expressible in TypeScript. 
I don't see a way to accommodate this type of model in general, as it allows for true type-changes (i.e. `string` becomes `number`, and so on), not just for narrowing, as in the solution Tomas suggested.

I'm afraid you'll have to adjust your model for cds-typer to play nicely with it.
You could try pulling all properties that are common in `Orders` and `FinishedOrders` into some sort of `OrdersCore` entity and associate to that, to employ a compositional pattern. Or remodel your entities to be actual narrowing.

Is either of that an option for you?

Best,
Daniel

**Comment by aschmidt93** [comment]
Hi,

adjusting the model seems to be the way to go.
