### ISSUE TITLE
[BUG] Duplicate Identifier generated when using many to many Composition

### ISSUE THREAD

**Issue by MichaelFlucher** [cap-js/cds-typer#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

The generated types of the `SampleService` include an empty type `Teams` and a class `Teams`, causing the error `Duplicate identifier 'Teams'.`

```
export type Teams = {};
export class Teams extends Array<Team> {$count?: number}
```

### Expected Behavior

Don't include `export type Teams = {};` or don't cause an typescript error

### Steps To Reproduce

1. Include the many-to-many sample in the database schema.cds
2. Expose both entities in the Service
3. Generate the types

### Environment

```markdown
- **OS**: macOS
- **Node**: 20.12.2
- **npm**: 10.8.0
- **cds-typer**: 0.25.0
- **cds**: 8.2.1
```

### Repository Containing a Minimal Reproducible Example

https://github.com/MichaelFlucher/cds-typer-issue

### Anything else?

It works if we don't expose the entity containing the Composition:
https://github.com/MichaelFlucher/cds-typer-issue/blob/working-sample/srv/sample-service.cds

**Comment by MichaelFlucher** [comment]
Sample code for many-to-many relationship taken from https://cap.cloud.sap/docs/cds/cdl#for-many-to-many-relationships

**Comment by daogrady** [comment]
Hi Michael,

thanks for reporting this issue and for attaching a minimal reproducible sample!
I have prepared [a fix](https://github.com/cap-js/cds-typer/pull/339) for this problem. Feel free to [try it out](https://github.com/cap-js/cds-typer/wiki/Trying-Out-Prerelease-Versions) before I merge it.

Best,
Daniel

**Comment by MichaelFlucher** [comment]
Hi Daniel,
I testet it with the sample and also in a bigger project. Works in both cases 👍🏽
