### ISSUE TITLE
Bug : index.ts file contains error when the aspect elements are used in event parameters. 

### ISSUE THREAD

**Issue by ilhanburak** [cap-js/cds-typer#32]
Hello,
When the aspect elements are used in event parameters , @cds-models/index.ts file contains the following error. 
`
export type [object Object] = {};
`  

db/schema.cds ( the _cuid_ aspect is used) 
```
using {
  Currency,
  managed,
  cuid,
  sap
} from '@sap/cds/common';

namespace sap.capire.bookshop;
entity Books : cuid, managed {
  @mandatory title  : localized String(111);
  descr             : localized String(1111);
  @mandatory author : Association to Authors;
  genre             : Association to Genres;
  stock             : Integer;
  price             : Decimal;
  currency          : Currency;
  image             : LargeBinary @Core.MediaType: 'image/png';
}
```

In _CatalogService_ cds file, _OrderedBook_ event parameter _book_ referenced from Book:ID . 
```

using { sap.capire.bookshop as my } from '../db/schema';
service CatalogService {

  /** For display in details pages */
  @readonly entity Books as projection on my.Books { *,
    author.name as author
  } excluding { createdBy, modifiedBy };

  event OrderedBook : { book: Books:ID; quantity: Integer; buyer: String };
}
```

Regards.
ilhan Burak

**Comment by daogrady** [comment]
Hi ilhan,

thanks for reporting this! I had not considered the `event` syntax up to this point. I will make sure to support it asap.

Best,
Daniel

**Comment by daogrady** [comment]
Hi ilhan,

I have opened a [feature branch](https://github.com/cap-js/cds-typer/tree/feat/events) on which the `event` syntax is supported. The feature is tested and should work, but since you reported this issue, would you like to check it out and make sure it fixes your issue before it is released?
If you need help setting a local test let me know!

Best,
Daniel

**Comment by ilhanburak** [comment]
Hello @daogrady,
I have checked with feature branch and looks fixed. 
Thanks.
ilhan burak.
