### ISSUE TITLE
[BUG] Missing option to pass CLI options to typer during 'cds build'

### ISSUE THREAD

**Issue by stockbal** [cap-js/cds-typer#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

I added the new cli option `--useEntitiesProxy true` to my VS Code settings (i.e. `"cds.typeGenerator.command"`) and during development the types are getting generated correctly.

However, during the build, cds-typer is using the function `compileFromFile` directly and only passes the output directory as option. This results in not having the proxy exports in the final cds build output.

### Expected Behavior

Some central way to specify cds-typer parameters that are used during development and during build, so the generated types output between dev and build does not differ.

### Environment

```markdown
| Module                 | Version |
| ---------------------- | --------|
| @cap-js/asyncapi       | 1.0.2   |
| @cap-js/cds-typer      | 0.26.0  |
| @cap-js/cds-types      | 0.2.0   |
| @cap-js/change-tracking| 1.0.7   |
| @cap-js/hana           | 1.2.0   |
| @cap-js/openapi        | 1.0.5   |
| @cap-js/sqlite         | 1.7.3   |
| @sap/cds               | 8.2.1   |
| @sap/cds-compiler      | 5.2.0   |
| @sap/cds-dk            | 8.2.0   |
| @sap/cds-dk (global)   | 7.9.6   |
| @sap/cds-fiori         | 1.2.7   |
| @sap/cds-foss          | 5.0.1   |
| @sap/cds-mtxs          | 2.1.0   |
| @sap/eslint-plugin-cds | 3.0.4   |
| Node.js                | v20.16.0|
```

**Comment by daogrady** [comment]
Hi Ludwig,

thanks for pointing this out. I have some good news, then some bad news, then some more good news:
cds-typer can be fully configured using `cds.env`. More specifically, you can place any of the relevant options under `cds.env.typer` just as you would pass them in as parameters. Those should then be picked up by cds-typer, regardless of whether you run it from the IDE or as part of your build process. But as I have recently found out, camelCased environment options can not be used in all constellations for technical reasons. I am therefore currently [in the process](https://github.com/cap-js/cds-typer/pull/324) of allowing any option to be passed in both camelcase and snake_case.

Best,
Daniel

**Comment by daogrady** [comment]
Hi Ludwig,

I have now merged the configuration via snake case, so it is available in `main` now if you would like to confirm this works.

Best,
Daniel

**Comment by stockbal** [comment]
Hi Daniel,

I checked it and it works. I configured it via `cds` in my package.json.

```json
...
"cds": {
   "typer": {
      "useEntitiesProxy": "true",
      "outputDirectory": "@cds-models"
    }
}
...
```

but as you can see, I also have to configure the `outputDirectory` in the env, otherwise the cds-typer build-plugin fails, as the output directory is ignored:

`/cds-plugins.js`
![image](https://github.com/user-attachments/assets/488cca87-ba4d-4af5-a0d0-9fbdd3a62a72)

`/lib/compile.js`
![image](https://github.com/user-attachments/assets/55af523e-edde-4ab7-8dfb-928086f56f60)

**Comment by daogrady** [comment]
Hi Ludwig,

thanks for pointing this out! I will revisit the build-plugin, which was not built with dynamic configuration in mind.

Best,
Daniel

**Comment by daogrady** [comment]
Hi Ludwig,

I have attached a [PR](https://github.com/cap-js/cds-typer/pull/334) to prioritise configuration passed through `cds.env`. If you would like to check it before I merge, just let me know.

Best,
Daniel

**Comment by stockbal** [comment]
Hi Daniel,

i left you a comment on the PR.

Regards,
Ludwig
