### ISSUE TITLE
[BUG] cds.entities not a function

### ISSUE THREAD

**Issue by GoldSucc** [cap-js/cds-typer#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

const csn = cds.entities('EquipmentService')
this is a part of generated file (js). in cds source I see that entities is actually object
`export class entity extends struct<'entity'> `
in runtime error happens when interaction with service happens:
```
    const equipmentService = await connect.to(EquipmentService);
    const query = SELECT.one.from(Equipment, "10000002");
    const equipment = (await equipmentService.run(query)) as Equipment;
```
because js file is used

### Expected Behavior

proper generation of js counterpart

### Steps To Reproduce

1. Define service cds with entity
2. Generate types
3. Build (tsc)
4. Query service in typed fashion as I shown in previous sections

### Environment

```markdown
- **OS**: MacOS 14
- **Node**: 22.8
- **npm**: 10.8
- **cds-typer**: 0.26
- **cds**: 8.2.2
```

**Comment by GoldSucc** [comment]
Note: replacing types with string:
```
    const equipmentService = await connect.to("EquipmentService");
    const query = SELECT.one.from("Equipment", "10000002");
    const equipment = (await equipmentService.run(query)) as Equipment;
```
fixes error. so it is definitely generated file error `const csn = cds.entities('EquipmentService')`

**Comment by GoldSucc** [comment]
@daogrady npx @cap-js/cds-typer "*"

**Comment by daogrady** [comment]
Hi Olegs,

I meant how you are importing the types in your service implementation. So basically what is above the code you showed in your initial snippet.

Best,
Daniel

**Comment by daogrady** [comment]
More specifically, the error reads as if you used top level imports to import the generated types to your service implementation.
If your imports look anything like this:

```js
// top of implementation file
const { ... } = require('#cds-models/...')
```

or

```ts
// top of implementation file
import * as ... from '#cds-models/...'
```

then please check the [CAPire section](https://cap.cloud.sap/docs/tools/cds-typer#subpath-imports) related to imports.
If that applies to you, I'd also like to point out the latest configuration option `--useEntitiesProxy` for cds-typer, which allows top-level imports in most scenarios.

**Comment by GoldSucc** [comment]
@daogrady yes, you are right. im using top level statements. I have ts configured to compile it to commonjs es6 so it worked after compilation but is a problem when executed by jest-ts node ts runtime. thank you. I will check if it works with this new flag

**Comment by tklein1801** [comment]
@GoldSucc If you want to automatically apply this flag, you can add the following to your settings.json in either VS Code or BAS settings. This will ensure that types are generated with the flag:

```json
{
    "cds.typeGenerator.command": "node \"${typerBinary}\" \"${targetFile}\" --outputDirectory \"${outputDirectory}\" --useEntitiesProxy true"
}
```

**Comment by daogrady** [comment]
Also, if you want to configure this behaviour project-wide for all contributors, you can [put it into your `cds.env`](https://cap.cloud.sap/docs/tools/cds-typer#configuration).
