### ISSUE TITLE
[BUG] namespace missing in CQL queries

### ISSUE THREAD

**Issue by geert-janklaps** [cap-js/cds-typer#37]
I'm currently working on switching a project to the new typescript approach using @cap-js/typer. 
Unfortunately, when using the newly generated types it looks like the namespace is missing when performing CQL queries.

I'm using the same approach as described [here](https://cap.cloud.sap/docs/tools/cds-typer#cql) in the documentation.

![image](https://github.com/cap-js/cds-typer/assets/2744548/6a29fbde-9cb7-473e-9885-f97423667b5c)

Also mentioned in following community question: https://answers.sap.com/questions/13938363/cap-typescript.html

## Details

Versions used:
```
@cap-js/cds-typer: 0.5.0
@cap-js/sqlite: 1.0.1
@sap/cds: 7.1.0
@sap/cds-compiler: 4.0.2
@sap/cds-dk: 7.0.3
@sap/cds-dk (global): 7.0.3
@sap/cds-fiori: 1.0.0
@sap/cds-foss: 4.0.2
@sap/cds-mtxs: 1.9.2
@sap/eslint-plugin-cds: 2.6.3
@thevaluechain/cap-number-range: 1.1.5
Node.js: v16.19.0
home: /home/user/projects/icm-reuse-numberrange/node_modules/@sap/cds
```

## Sample Code

Sample Model

```cds
using { User, cuid, managed } from '@sap/cds/common';
namespace eu.thevaluechain.common.numberrange.db;

@singular: 'NumberRangeObject'
@plural: 'NumberRangeObjects'
@assert.unique: {object: [Object]}
entity NumberRangeObjects : cuid, managed {
    Object: String(10) @mandatory;
    Description: String(40);
    NumberLength: Decimal(2,0);
    WarningPercentage: Integer;
    Prefix: Boolean;
    Intervals: Composition of many Intervals on Intervals.Object=$self;
}

@singular: 'Interval'
@plural: 'Intervals'
@assert.unique: {objectnumber: [Object,NumberRangeNo]}
entity Intervals : cuid, managed {
    Object: Association to one NumberRangeObjects;
    NumberRangeNo: UInt8 @mandatory;
    Description: String(40);
    NumberFrom: Integer64 @mandatory;
    NumberTo: Integer64 @mandatory;
    IntervalStatusses: Association to many IntervalStatusses on IntervalStatusses.Interval=$self;
}

@singular: 'IntervalStatus'
@plural: 'IntervalStatusses'
@assert.unique: {intervalprefix: [Interval,Prefix]}
entity IntervalStatusses : cuid, managed {
    Interval: Association to one Intervals;
    Prefix: String(4) @readonly;
    NumberStatus: Integer64 @readonly @Core.Immutable;
}
```

Sample Code

```typescript
const {NumberRangeObject, Intervals} = require('../../@cds-models/eu/thevaluechain/common/numberrange/db')

// Get number range object configuration
this._numberRangeObject = await SELECT.one.from(NumberRangeObject).where({ID: this._numberRangeObjectID});
if(!this._numberRangeObject){
      throw new Error("Number Range Object not found!");
}
this._numberRangeObject.Intervals = await SELECT.from(Intervals).where({Object_ID: this._numberRangeObjectID });
```

[^1]: You can acquire the version of `cds-typer` you are using by executing: `npx cds-typer --version`
[^2]: A repository to your project where the problem manifests (including the relevant branch).
[^3]: These versions can be acquired by running `cds v -i`. May not apply to you, in that case just leave it blank.

**Comment by daogrady** [comment]
Hi Geert-Jan,

that does look odd, yes.
Do you think you could share a bit more information, like (parts of) the model you were using to generate the types?

Best,
Daniel

**Comment by daogrady** [comment]
Hi Geert-Jan,

thanks for adding the model! I will look into it asap.

Best,
Daniel

**Comment by daogrady** [comment]
I am just looking into it and I have a hard time reproducing the error. Could you please verify that the types you are importing are actually in the place you expect them to be? I.e. <kbd>ctrl</kbd> + left click the path within your `require` to see if it leads you to the `index.ts` file that contains the types.

(btw. you can use `require('#cds-models/eu/thevaluechain/common/numberrange/db')` to spare yourself the trouble of using relative paths everywhere if you installed cds-typer using the facet 🙂)

**Comment by geert-janklaps** [comment]
Just tested the ctrl + left click, which is working perfectly fine :)
I switched to  the relative paths just for testing and making sure that everything was working fine. (I used the facet approach for setting up the cds-typer)

Is there any other information that I can provide that might be helpful for you to try to reproduce this issue?

**Comment by daogrady** [comment]
If you are able to provide a minimal reproducible example in a separate repository where I can observe the behaviour, that would be of great help!

**Comment by geert-janklaps** [comment]
I just added you to the repository which is presenting with this issue. (**branch: cds-typer**)
It's a quite straight forward process to reproduce this issue:
1. Start the server with: npm run watch:dev
2. Open the action.http file and execute the second request (action Get Next Number)

This will cause error "no such table: NumberRangeObjects in:\nSELECT * FROM NumberRangeObjects WHERE Object = ? LIMIT 1"

**Comment by daogrady** [comment]
Awesome, I will check it asap, thanks!

**Comment by daogrady** [comment]
Hi Geert-Jan,

I just tried out your (very well detailed!) repro and I am afraid it works on my computer(TM) 😬
Running the Postman action returns:

```http
HTTP/1.1 200 OK
X-Powered-By: Express
X-Correlation-ID: a2888b7b-41c2-420c-af97-d0cbe051631b
OData-Version: 4.0
content-type: application/json;odata.metadata=minimal
Date: Wed, 02 Aug 2023 16:28:39 GMT
Connection: close
Content-Length: 62

{
  "@odata.context": "$metadata#Edm.String",
  "value": "2510000001"
}
```

And I can step over the assignment of `numberrangedb` and see that it is being filled in in the debugger:

![Screenshot 2023-08-02 at 18 29 49](https://github.com/cap-js/cds-typer/assets/103028279/c55c0005-e9b7-4e5d-96ca-a87b586c2e08)

Could you maybe to a clean checkout of your project and see if the errors persists for you? Just to make sure there isn't some weird cache-effect going on.

Best,
Daniel

**Comment by geert-janklaps** [comment]
Hi Daniel,

I'll try that again, but this is what I did yesterday! :)
Can this be related to the fact that I'm using SAP Business Application Studio? (e.g. node version is 16.19 -> something which can't be changed)

Best regards,
Geert-Jan

**Comment by geert-janklaps** [comment]
Hi Daniel,

Seems to be an issue with caching or something like that at least, I created a completely new workspace in BAS and now is does seem to be working. (in my original workspace, uninstalling and re-installing all modules didn't solve the issue)
I'll close the issue, I don't think it's worth diving into the details as this does work in a new workspace. (the previous workspace was already +1 year old, so over time maybe something went wrong with the configuration)

Thanks for the support on this one!

Best regards,
Geert-Jan
