### ISSUE TITLE
[BUG] Unable to run with cds-tsx

### ISSUE THREAD

**Issue by LaserHydra** [cap-js/cds-typer#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When running my project using the new beta cds-tsx, I am getting the following error.
```
TypeError: Class extends value undefined is not a constructor or null
    at _cuidAspect (...\@cds-models\index.ts:12:29)
    at <anonymous> (...\@cds-models\index.ts:23:27)
    at Object.<anonymous> (...\@cds-models\index.ts:57:59)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Object.transformer (...\AppData\Roaming\npm\node_modules\tsx\dist\register-DCnOAxY2.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at <anonymous> (...\@cds-models\a41g\checkoutsolution\index.ts:3:20)
```
Also debugging this issue, it seems that the `__` import is not working as expected, as it remains undefined.
`import * as __ from './../_';`

Furthermore, according to the debugger, while the service definitions are included via their typescript files, the base import from the `_` directory seems to only include the index.js at runtime here. Since this file is lacking the typescript definitions, it appears that this would be the cause for the error above. However I am not sure why this is happening.
![grafik](https://github.com/user-attachments/assets/ee0aa352-2e8d-4f1c-8cda-37b640eb7ab3)

The same project works fine by only replacing cds-tsx with cds-ts.

### Expected Behavior

I would expect to be able to run my project including CDS Typer with cds-tsx without issues as with cds-ts.

### Environment

```markdown
- **OS**: Windows 11 Build 22631
- **Node**: v20.18.0
- **npm**: 10.8.2
- **cds-typer**: 0.26.0
- **cds**: 8.3.0
```

**Comment by daogrady** [comment]
Hi Oliver,

thanks for reporting this issue. We are currently working on getting `cds-tx` to work with the files emitted by cds-typer.
One solution seems to be to adjust the tsconfig.json:

```patch
-      "#cds-models/*": ["./@cds-models/*/index.ts"]
+      "#cds-models/*": ["./@cds-models/*"]
```

Could you please try that and let me know if that resolved your issue?

Best,
Daniel

**Comment by LaserHydra** [comment]
Hi @daogrady,

Thank you for your response.
I actually had the following combination in my tsconfig:
```
"#cds-models/*": [
      "./@cds-models/*/index.ts",
      "./@cds-models/*"
]
```
Interestingly I am unable to reproduce my issue again at the moment, with neither definition.
I will get back to you, if I do run into the issue again and can verify your suggestion.

Thank you,
Oliver

**Comment by daogrady** [comment]
Hi Oliver,

glad to hear this got resolved for now! I'd then like to close this issue. Feel free to reopen it or open a new one in case you run into it again.

Best,
Daniel

**Comment by LaserHydra** [comment]
I have just run into the same issue again.

Changing my tsconfig from
```json
"#cds-models/*": [
      "./@cds-models/*/index.ts",
      "./@cds-models/*"
]
```
to
```json
"#cds-models/*": [
      "./@cds-models/*"
]
```

seems to have helped resolve the issue for the time being 😄 

Thanks again
