### ISSUE TITLE
[QUESTION] Actions not working with imports after deployment

### ISSUE THREAD

**Issue by MarvinWeitz** [cap-js/cds-typer#384]
### Question

Hi everyone. I have a problem regarding actions.

I am using a simple test action
```cds
service ProcessorService {
    // Some entities

    action test() returns String;
}
```

that I want to define in my `service.ts`

```ts
import { test } from '#cds-models/ProcessorService'

export class ProcessorService extends ApplicationService {
    async init() {
        this.on(test, (req: Request) => {
            console.log("Test")
        })

        return super.init()
    }
}
```

This works locally when trying it locally via `cds-ts watch` but after building the mta via `mta build` and deploying it to cf via `cf deploy test.mtar`, the ProcessorService is not able to load (It doesn't show any data in the ListView I am using). 
It also failes when using `require` as staed in the [docs](https://cap.cloud.sap/docs/tools/cds-typer#actions)
It does however work when I use the quoted action name `this.on("test", (req: Request) => {...}`.

What could be the cause of this problem?

**Comment by MarvinWeitz** [comment]
Yes, this is the case. I just checked what the `.mtar` file contains after performing `mbt build`. The main files (shortened):

_./srv/services.js_:
```js
const cds_1 = require("@sap/cds");
const ProcessorService_1 = require("#cds-models/ProcessorService");
class ProcessorService extends cds_1.ApplicationService {
    async init() {
        this.on(ProcessorService_1.test, async (req) => {...}
    }
```
_./package.json_:
```json
{
    "imports": {
         "#cds-models/*": "./@cds-models/*/index.js"
    }
}
```
_./@cds-models/ProcessorService/index.js_:
```js
// This is an automatically generated file. Please do not change its contents manually!
const cds_1 = __importDefault(require("@sap/cds"));
const __ = __importStar(require("./../_"));
class ProcessorService extends cds_1.default.Service {
}
exports.ProcessorService = ProcessorService;
exports.default = ProcessorService;
```
With no sign of `test` in sight...

**Comment by daogrady** [comment]
Hi Marvin,

this actually looks like the final step of copying the untranspiled JS files over the transpiled ones in the build step has not run properly in your case. Could you please provide a repository with a minimal working sample so I can reproduce the issue for your particular case?

Best,
Daniel

**Comment by MarvinWeitz** [comment]
Hi, sorry for not answering on this for so long. Didn't have the time to investigate / create a repo. But I now figured out, that the problem was `tsc` was run in the build process of the mta after type generation, which compiled the `index.ts` files into `index.js` and broke the references. removing `tsc` at this point fixed the issue!
