### ISSUE TITLE
[QUESTION] Properties of response in capital letters?

### ISSUE THREAD

**Issue by thisisevanfox** [cap-js/cds-typer#39]
## Description
In some places in our project we read data using a transaction with the read function. With cds-typer all properties in the response come back in capital letters. In the entity definition we use camel case and also in the generated index file camel case is used, which then leads to problems when processing the response.

Originally we had cds2types in use, here the properties of the response were - as in the definition - camel case. Is this behavior intended, that all properties of the response are in capital letters and we have to adapt the processing of the response or is there an error or can we influence the "format" of the response somehow?

![image](https://github.com/cap-js/cds-typer/assets/43059689/aac11e39-3913-4aa3-84c1-b5c6b37fec08)
![image](https://github.com/cap-js/cds-typer/assets/43059689/860a0868-ad7d-4eda-8375-c48dd3d1c6b0)

## Details

**Versions of CDS tools:**
![image](https://github.com/cap-js/cds-typer/assets/43059689/a73c8491-3294-4616-9bbd-51085739cef1)
**Version of `cds-typer`:** 0.5.0

## Sample CDS
![image](https://github.com/cap-js/cds-typer/assets/43059689/45c80d1a-c6fa-4551-bc89-8e91ca72f9c8)

## Generated index.ts
![image](https://github.com/cap-js/cds-typer/assets/43059689/a41d2cc3-051b-447d-9efa-ff9f0b69684d)

**Comment by daogrady** [comment]
Hi Evan,

thanks for reporting this quirk. This is definitely not intended behaviour.
Could you please add a sample of the read-call that  is producing this output?

Best,
Daniel

**Comment by thisisevanfox** [comment]
Hi Daniel,

Which read call should I send you? Does this screenshot help?

![image](https://github.com/cap-js/cds-typer/assets/43059689/296af87e-e485-4c7a-9d2e-afc9b3877251)

Kind regards,
Johannes

**Comment by daogrady** [comment]
Hi Johannes,

this is also helpful, yes. I assume you have something like `await SELECT...` somewhere in your code. Can you disclose that snippet? Feel free to obfuscate sensitive parts, of course!

Best,
Daniel

**Comment by thisisevanfox** [comment]
Hi Daniel,

here's the code snippet - no magic at all. We are doing something like this:

```ts
const entries = await tx.run(SELECT.from("MYENTITY").where({ Id: myId }));
```

Kind regards,
Johannes

**Comment by daogrady** [comment]
Hi Johannes,

thanks for the snippet! I am actually a bit surprised that the name of your entity seems to be capitalised as well. Is that actually how it is in your code, or did you just add it for the example?

Best,
Daniel

**Comment by thisisevanfox** [comment]
Hi Daniel,

It's just for the example. I just tried it with lowercase - the result stays the same.

Kind regards,
Johannes

**Comment by daogrady** [comment]
If you are using a string inside the `SELECT(...)` (as opposed to using the generated types `SELECT(MyEntity)`, then it is extra weird. The generated types have no influence on the runtime then whatsoever. Especially since the screenshot of the generated types actually shows the properties to be properly set in camel case.
Can you please double-check that switching between cds2types and cds-typer really is the culprit that causes this behaviour?
Alternatively, you can of course provide a minimal sample in which I can observe this behaviour so I can check for myself.

**Comment by thisisevanfox** [comment]
Hi Daniel,

I cannot reproduce the issue in the bookshop example and i think my application is too complex to post a MWE here. 

Nevertheless i debugged through my node modules and had the following finding in the hdb-module (version 0.19.3): There is a difference in the "columnDisplayName" which is extracted from the buffer read from the db (when I get the coding right there).

![image](https://github.com/cap-js/cds-typer/assets/43059689/4542238a-d49b-47ee-ab1f-172c00f378a6)
![image](https://github.com/cap-js/cds-typer/assets/43059689/21043091-9d24-4d23-b9ca-b7c23f468806)

Do you have any idea how this property is affected by the used type generator?

**Comment by daogrady** [comment]
Hi Johannes,

thanks for taking the time to debug into the modules. This is all very peculiar. Since your app is apparently to large to reduce and presumably not sharable, we need to somehow narrow down the possible root cause, as this seems to be a highly situational issue. Can you provide an (informal) diff between what you are doing when using cds-typer vs cds2types?

Best,
Daniel

**Comment by daogrady** [comment]
Hi Johannes,

did you have time to look into the diff or did you maybe even find a solution for this issue?

Best,
Daniel

**Comment by thisisevanfox** [comment]
Hi Daniel,

we don't have a solution yet, but we haven't had a chance to try a few things. If there are any new findings, I'll share them here.

Regarding your question: We didn't change much, only the dependency in the package.json and of course the imports of the type definitions.

Kind regards,
Johannes

**Comment by daogrady** [comment]
Hi Johannes,

I have approached one of our runtime experts about this problem and they suggested that the identifier you are passing into your `SELECT` might not be matching your actual model name.
Usually, you'd pass in a fully qualified model name, i.e. `SELECT.from('sap.cap.bookshop.Books')`[^1]. If that parameter can not be resolved against the model, then the runtime can not perform a mapping of the database columns, which are in all upper case, to how the names are written in the model.
Please double check that you pass in a fully qualified name of an entity or use `SELECT.from(Books)` without quotes, given that `Books` is an import from your model.

Best,
Daniel

**Comment by thisisevanfox** [comment]
Hi Daniel,

thank you for your efforts.  We were able to do some tests now. When we pass the entity  to the select (like `SELECT.from(Books)`) we get the error: `Could not find table/view BOOKS in schema <SCHEMA_ID>`. The issue here is that the table on the database is named "MYMODEL_BOOKS".

When we call `SELECT.from('sap.cap.bookshop.Books')` it works. The elements in the response are not capitalized.

We have several service definitions in our `service.cds`. 
```cds
using mymodel as mymodel from '../../db/data-model';
using {sap} from '@sap/cds/common';

service MyService @(requires: 'authenticated-user') {
     entity Customers as projection on mymodel.Customer;
     entity Cars as projection on mymodel.Car  {
          *,
         Customers: redirected to Customers
    };
}
```

Note that this example is really simplified, we want to serve denormalized views with our service.cds file like described [here](https://cap.cloud.sap/docs/guides/providing-services#serving-denormalized-views).

The `data-model.cds` looks like this:
```cds
using {managed} from '@sap/cds/common';

namespace mymodel;

entity Customer: managed {
    key Id : UUID;
        Name : String(256);
        Cars: Association to many Car on Cars.Customer= $self;
}

entity Car: managed {
    key Id  : UUID;
        Brand : String(256);
        Customer : Association to one Customer;
}
```

After running cds-typer the MyService `index.ts` file looks like this 
```typescript
import * as _mymodel from './../mymodel';
import * as __ from './../_';
import * as _ from './..';

// other entites

export function _CarAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Car extends Base {
        Id?: string;
        Brand?: string;
        Customer?: __.Association.to<_mymodel.Customer>;
  };
}
export class Car extends _._managedAspect(_CarAspect(__.Entity)) {}
export class Cars extends Array<Car> {}
```
The `index.ts` file for my model looks like this:
```typescript
import * as __ from './../_';
import * as _ from './..';

// other entities

export function _CustomerAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Customer extends Base {
        Id?: string;
        Name?: string;
        Cars?: __.Association.to.many<Cars_>;
  };
}
export class Customer extends _._managedAspect(_CustomerAspect(__.Entity)) {}
export class Customer_ extends Array<Customer> {}

export function _CarAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Car extends Base {
        Id?: string;
		Brand?: string;
        ColorCustomizingSet?: __.Association.to<Customer>;
  };
}
export class Car extends _._managedAspect(_CarAspect(__.Entity)) {}
export class Car_ extends Array<Car> {}
```

As we want to read our denormalized views like described above, we are doing something like this in our coding as opposed to reading directly from the datamodel:
```typescript
// select from entity from the datamodel
SELECT.from("mymodel.Car"); // no capital letters in response
// select from view defined in service.cds
SELECT.from("MYSERVICE.Cars"); // capital letters in response 
```

We think that there is something wrong when generating the types for entities/views which are only defined in the `service.cds` file. Additional information: When reading like described, we are not inside an OData handler but in a RESTful endpoint.

I'm out of office for the next few days, so maybe my colleague @dnzxy will deal with this topic, if you can find time to fiddle around with this topic. No pressure at all.

Thank you & Kind regards,
Johannes

**Comment by daogrady** [comment]
Hi Johannes, hi Deniz,

I tried reproducing the behaviour from the listings you provided, but I fail to run into the issues you are describing.

```js
class MyService extends cds.ApplicationService { async init() {
    this.on('READ', '*', async () => {
        const { Customer } = require('#cds-models/mymodel')
        console.log(await SELECT.from(Customer))
    })
}}
```
prints:
```js
[
  {
    createdAt: null,
    createdBy: '2023-08-22T05:40:46.812Z',
    modifiedAt: null,
    modifiedBy: '2023-08-22T05:40:46.812Z',
    Id: '0',
    Name: 'Foo'
  }
]
```
Which is the sole entry I provided as data set. Note that the column names are not in all-caps.

I think as of now we are merely poking in the dark until the issue becomes reproducible. Could you please provide a fully self-contained sample repository where I can observe the behaviour?

Best,
Daniel
