### ISSUE TITLE
[BUG] [REGRESSION] Regressions in `v0.28`: missing `declare` modifier for `.actions`

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-typer#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Issues introduced in the latest version of the library:
- Issue with `actions` override.
Generated code:
```ts
export function _LanguageAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Language extends _CodeListAspect(Base) {
    /** Type for a language code */
    declare code?: __.Key<Locale>
    static override readonly kind: "entity" | "type" | "aspect" = 'entity';
    declare static readonly keys: __.KeysOf<Language>;
    declare static readonly elements: __.ElementsOf<Language>;
    static readonly actions: typeof CodeList.actions & Record<never, never>;
  };
}
export function _CodeListAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class CodeList extends Base {
    declare name?: string | null
    declare descr?: string | null
    static readonly kind: "entity" | "type" | "aspect" = 'aspect';
    declare static readonly keys: __.KeysOf<CodeList>;
    declare static readonly elements: __.ElementsOf<CodeList>;
    static readonly actions: Record<never, never>;
  };
}
```
Error: 
```
X [ERROR] TS4114: This member must have an 'override' modifier because it overrides a member in the base class '_CodeListAspect<TBase>.CodeList & object'.

    ../models/sap/common/index.ts:66:20:
      66 │     static readonly actions: typeof CodeList.actions & Record<neve...
         ╵                     ~~~~~~~
```
- Issue with changed function return type:
Before update:
```ts
export declare const getGoogleCalendarEvents: { (start: string, end: string): _.GoogleCalendarEvents | null, __parameters: {start: string, end: string}, __returns: _.GoogleCalendarEvents | null, kind: 'function'};
```
After update:
```ts
export declare const getGoogleCalendarEvents:  {
          // positional
          (start: string, end: string): Promise<_.GoogleCalendarEvents | null> | _.GoogleCalendarEvents | null
          // named
          ({start, end}: {start: string, end: string}): Promise<_.GoogleCalendarEvents | null> | _.GoogleCalendarEvents | null
          // metadata (do not use)
          __parameters: {start: string, end: string}, __returns: Promise<_.GoogleCalendarEvents | null> | _.GoogleCalendarEvents | null
          kind: 'function'
        }
```
Why does the return type now includes `Promise<_.GoogleCalendarEvents | null>`? Looks wrong and breaks my code.

- Issue with incorrect class extension:
Generated code:
```ts
export function _LeadAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Lead extends _._cuidAspect(_._managedAspect(_._oldCrmIdAspect(Base))) {
    declare status?: _.LeadStatus | null
    declare source?: _.LeadSource | null
    declare company?: __.Composition.of<Company> | null
    declare company_ID?: __.Key<string> | null
    declare assignedTo?: _gc_crm_types.User | null
    declare assignedTo_ID?: __.Key<string> | null
    static override readonly kind: "entity" | "type" | "aspect" = 'entity';
    declare static readonly keys: __.KeysOf<Lead>;
    declare static readonly elements: __.ElementsOf<Lead>;
    static readonly actions: typeof _.oldCrmId.actions & typeof _.managed.actions & typeof _.cuid.actions & Record<never, never>;
  };
}
export function _cuidAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class cuid extends Base {
    declare ID?: __.Key<string>
    static readonly kind: "entity" | "type" | "aspect" = 'aspect';
    declare static readonly keys: __.KeysOf<cuid>;
    declare static readonly elements: __.ElementsOf<cuid>;
    static readonly actions: Record<never, never>;
  };
}
```
Error:
```
X [ERROR] TS2417: Class static side '{ new (...args: any[]): Lead; prototype: _LeadAspect<any>.Lead; readonly kind: "entity" | "type" | "aspect"; readonly keys: KeysOf<Lead>; readonly elements: ElementsOf<...>; readonly actions: Record<...>; } & TBase' incorrectly extends base class 
static side '{ prototype: _cuidAspect<any>.cuid; readonly kind: "entity" | "type" | "aspect"; readonly keys: KeysOf<_cuidAspect<{ new (...args: any[]): _managedAspect<{ new (...args: any[]): _oldCrmIdAspect<TBase>.oldCrmId; ... 4 more ...; readonly actions: Record<...>; } & TBase>.managed; ... 4 more ...; readonly actions: Recor...'.
  Type '{ new (...args: any[]): Lead; prototype: _LeadAspect<any>.Lead; readonly kind: "entity" | "type" | "aspect"; readonly keys: KeysOf<Lead>; readonly elements: ElementsOf<...>; readonly actions: Record<...>; } & TBase' is not assignable to type '{ prototype: _cuidAspect<any>.cui
d; readonly kind: "entity" | "type" | "aspect"; readonly keys: __.KeysOf<_cuidAspect<{ new (...args: any[]): _managedAspect<{ new (...args: any[]): _oldCrmIdAspect<TBase>.oldCrmId; ... 4 more ...; readonly actions: Record<never, never>; } & TBase>.managed; ... 4 more ...; readonly ac...'.
    Types of property 'keys' are incompatible.
      Property 'ID' is missing in type 'KeysOf<Lead>' but required in type 'KeysOf<_cuidAspect<{ new (...args: any[]): _managedAspect<{ new (...args: any[]): _oldCrmIdAspect<TBase>.oldCrmId; prototype: _oldCrmIdAspect<any>.oldCrmId; readonly kind: "entity" | ... 1 more ... | "aspect"; readonly keys: KeysOf<...>; readonly elements: ElementsOf<...>; readonly actions: Record<...>; } & TBase>.m...'.

    ../models/gc/crm/index.ts:159:15:
      159 │   return class Lead extends _._cuidAspect(_._managedAspect(_._old...
          ╵                ~~~~

  'ID' is declared here.

    ../models/index.ts:311:12:
      311 │     declare ID?: __.Key<string>
          ╵             ~~
```
![error](https://github.com/user-attachments/assets/359eb8ea-296c-48e0-badd-7278467d8014)

### Expected Behavior

No errors after update.

### Environment

| Package            | Version                                                                              |
| ---------------------- | ----------------------------------------------------------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                                                                       |
| @cap-js/cds-typer      | 0.28.1                                                                                                       |
| @cap-js/cds-types      | 0.7.0                                                                                                       |
| @cap-js/openapi        | 1.0.7                                                                                                       |
| @cap-js/postgres       | 1.10.3                                                                                                      |
| @sap/cds               | 8.4.1                                                                                                       |
| @sap/cds-compiler      | 5.4.2                                                                                                       |
| @sap/cds-dk            | 8.4.1                                                                                                       |
| @sap/cds-dk (global)   | 8.4.1                                                                                                       |
| @sap/cds-fiori         | 1.2.7                                                                                                       |
| @sap/cds-foss          | 5.0.1                                                                                                       |
| @sap/cds-mtxs          | 2.3.0                                                                                                       |
| @sap/eslint-plugin-cds | 3.1.2                                                                                                       |
| Node.js                | v20.18.0                                                                                                    |

**Comment by daogrady** [comment]
Hi Tomas,

thanks for reporting this! I will look into the regression.
I am not sure why the change in return type from `X` to `X | Promise<X>` poses an issue. This change accommodates asynchronous actions and you can simply await them, even when they are not a `Promise`:

```ts
declare function fn (): Promise<number> | number 

const x = await fn()  // could be Promise, could be number
x.toExponential()  // now definitely number
```

Best,
Daniel

**Comment by hakimio** [comment]
We are using `ActionReturn` type extensively defined in `cds-ts-dispatcher` library:
https://github.com/dxfrontier/cds-ts-dispatcher/blob/4be4215c0e5bc4ed63aabad191a459607bc777a7/lib/types/types.ts#L73

The change breaks the type.
Even if this can be worked around by introducing a new custom type, it's still another major breaking change.

**Comment by daogrady** [comment]
This change was actually required as

1. actions could always have been asynchronous, there was just no way to declare it in CDS, so the return type was actually wrong before
2. actions have rarely been called before, but rather implemented via `service.on`. This has changed now, as calling an action has now become significantly more likely with the introduction of named parameters
3. even if this was not a 0 major version, the generated types very clearly state:

```ts
          // metadata (do not use)
```

yet `cds-ts-dispatcher` seems to rely on `__returns`. So I'd say we should instead inform the maintainers of `cds-ts-dispatcher` that this particular type has broken for their scenario (fyi https://github.com/dragolea).

Your complaint regarding the regression seems to be valid from the looks of it, so I'll address that part asap.

**Comment by hakimio** [comment]
> Your complaint regarding the regression seems to be valid from the looks of it, so I'll address that part asap.

Thank you.

**Comment by hakimio** [comment]
@daogrady is the issue with incorrect class extension fixed as well?

**Comment by daogrady** [comment]
Sorry, I overlooked that one. Could you please provide a minimal reproduction sample for the model?

**Comment by hakimio** [comment]
`Lead` model:
```cds
type LeadStatus                   : String enum {
    New;
    Appointment;
}

type LeadSource                   : String enum {
    Bot;
    User;
}

@assert.unique: {
    website: [website],
    cvr    : [cvr]
}
entity Companies : cuid, managed, oldCrmId {
    name        : String not null @mandatory;
    website     : String not null @mandatory;
    cvr         : String(50);
}

aspect oldCrmId {
    oldCrmId : Integer;
}

entity Users : cuid, managed {
    name         : String not null  @mandatory;
    username     : String not null  @mandatory;
    isActive     : Boolean default true;
}

type User                     : Association to Users;

entity Leads : cuid, managed, oldCrmId {
    status     : LeadStatus default 'New';
    source     : LeadSource default 'User';
    company    : Composition of Companies @mandatory;
    assignedTo : User;
}
```

**Comment by daogrady** [comment]
Thanks! I'll check it out.

**Comment by daogrady** [comment]
@hakimio I can not reproduce the error on my side. Can you please also provide your tsconfig.json?

**Comment by hakimio** [comment]
It's frontend's `tsconfig` where I only use the types:
```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noImplicitOverride": true,
        "noPropertyAccessFromIndexSignature": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "sourceMap": true,
        "declaration": false,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "importHelpers": true,
        "target": "ES2022",
        "module": "ES2022",
        "useDefineForClassFields": false,
        "isolatedModules": true,
        "lib": [
            "ES2023.Array",
            "ES2022",
            "dom"
        ],
        "baseUrl": "./src"
    }
}
```

TS version: `5.5.4`

**Comment by daogrady** [comment]
Judging from your screenshot, the problem seems to stem from the entity `Contract`, which is not included in the model you have provided so far. Please include that entity for reproducibility.

**Comment by hakimio** [comment]
It was the same error on a different entity. That's why it's not included. See the text version of the error where it's `Lead` instead of `Contract`.

**Comment by daogrady** [comment]
Calling `tsc --noEmit` with the model and _tsconfig.json_ you provided and cds-typer@0.28.1, I can only reproduce the errors regarding the missing modifier for `actions`. So there seems to be something missing for reproduction of the other error.

From the error message, could it be [a change in type of an existing property](https://github.com/cap-js/cds-typer#known-restrictions)?

**Comment by hakimio** [comment]
Ok, I'll investigate the error and let you know what exactly is causing it.

**Comment by hakimio** [comment]
Ok, I think I figured out what's causing the error.

Minimal CDS schema to reproduce the issue:
```cds
type CompanyType                  : String enum {
    Lead;
    Customer;
}

entity Customers : cuid {
    company              : Composition of Companies @mandatory;
}

entity Companies : cuid {
    name        : String not null @mandatory;
    website     : String not null @mandatory;
    companyType : CompanyType default 'Lead';
    customer    : Association to Customers
                      on  customer.company = $self
                      and companyType      = 'Customer';
}
```

Generated code:
```ts
export function _CustomerAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Customer extends _._cuidAspect(Base) {
    declare company?: __.Composition.of<Company> | null
    declare company_ID?: __.Key<string> | null
    static override readonly kind: "entity" | "type" | "aspect" = 'entity';
    declare static readonly keys: __.KeysOf<Customer>;
    declare static readonly elements: __.ElementsOf<Customer>;
    static override readonly actions: typeof _.cuid.actions & Record<never, never>;
  };
}
export class Customer extends _CustomerAspect(__.Entity) {}
Object.defineProperty(Customer, 'name', { value: 'gc.crm.Customers' })
Object.defineProperty(Customer, 'is_singular', { value: true })
export class Customers extends Array<Customer> {$count?: number}
Object.defineProperty(Customers, 'name', { value: 'gc.crm.Customers' })

export function _CompanyAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Company extends _._cuidAspect(Base) {
    declare name?: string
    declare website?: string
    declare companyType?: _.CompanyType | null
    declare customer?: __.Association.to<Customer> | null
    static override readonly kind: "entity" | "type" | "aspect" = 'entity';
    declare static readonly keys: __.KeysOf<Company>;
    declare static readonly elements: __.ElementsOf<Company>;
    declare static readonly actions: typeof _.cuid.actions & Record<never, never>;
  };
}
export class Company extends _CompanyAspect(__.Entity) {}
Object.defineProperty(Company, 'name', { value: 'gc.crm.Companies' })
Object.defineProperty(Company, 'is_singular', { value: true })
export class Companies extends Array<Company> {$count?: number}
Object.defineProperty(Companies, 'name', { value: 'gc.crm.Companies' })
```

It seems when the entities are referencing each other TS doesn't include the keys of inherited classes when constructing the type of `keys: __.KeysOf<...>`. As a result, TS thinks that the `Customer` class doesn't include the `ID` field and the `keys` properties become incompatible.

![image](https://github.com/user-attachments/assets/ede03652-a6b6-478e-a8ac-491eee9a3c3e)

Error msg:

```
TS2417: Class static side

{ new (...args: any[]): Customer; prototype: _CustomerAspect<any>.Customer; readonly kind: "entity" | "type" | "aspect"; readonly keys: KeysOf<Customer>; readonly elements: ElementsOf<...>; readonly actions: Record<...>; } & TBase

incorrectly extends base class static side

{ prototype: _cuidAspect<any>.cuid; readonly kind: "entity" | "type" | "aspect"; readonly keys: __.KeysOf<_cuidAspect<TBase>.cuid>; readonly elements: __.ElementsOf<...>; readonly actions: Record<never, never>; }

Types of property keys are incompatible.

Property ID is missing in type KeysOf<Customer> but required in type KeysOf<_cuidAspect<TBase>.cuid>
```

**Comment by daogrady** [comment]
Hi Tomas,

thanks for investigating further and finding the root cause of this issue! I can now reproduce the problem. The underlying issue seems to be pretty deeply rooted in how we emulate CDS aspects and model the `Key` type, but I will see if I can work around this.

Best,
Daniel

**Comment by daogrady** [comment]
Hi Tomas,

I prepared a solution which works for your minimal sample. Feel free to try it on your actual model before I merge it.

Best,
Daniel

**Comment by hakimio** [comment]
Thanks, Daniel. Will try it out ASAP.

**Comment by hakimio** [comment]
@daogrady I have tested the changes and now both issues seem to be fixed.

**Comment by daogrady** [comment]
Glad to hear, thanks for testing! I see to have out a new release by mid-week.
