### ISSUE TITLE
[BUG] version 0.29.0 generates on `mbt build` the cds-typer files on `./` 

### ISSUE THREAD

**Issue by dragolea** [cap-js/cds-typer#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When trying locally `mbt build` the `mbt` regenerates the `cds-typer` files outside of `./gen/srv/srv` even if the --outputDirectory options is used.

Please see the repository attached below, increse version to `0.29.0` and use `mbt build`.

<img width="235" alt="image" src="https://github.com/user-attachments/assets/3c93fd0b-1cd1-43dd-b16b-8ef968f72a89">

### Expected Behavior

To have the generated cds-typer inside of the `./gen/srv/srv`

### Environment

```markdown
- **Mac**:
- **v20.18.0**:
- **10.8.2**:
- **0.29.0**: 
- **8.4.2**:
```

### Repository Containing a Minimal Reproducible Example

https://github.com/dxfrontier/cds-ts-samples

**Comment by YoussefBoudiba** [comment]
I believe it's the same as this one: https://github.com/cap-js/cds-typer/issues/405

**Comment by daogrady** [comment]
Closed as duplicate, will release fix today.
