### ISSUE TITLE
[BUG] cds-typer error with Attachments aspect.

### ISSUE THREAD

**Issue by vc10812** [cap-js/cds-typer#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When using the Attachments plugin ([[cap-js/attachments: The @cap-js/attachments package is a CDS plugin that provides out-of-the box asset storage and handling by using an aspect Attachments. It also provides a CAP-level, easy to use integration of the SAP Object Store.](https://github.com/cap-js/attachments#readme)](https://github.com/cap-js/attachments#readme)) for SAP CAP, an error occurs with cds typer.

I contacted the Attachments developer and they confirmed there is an issue with cds typer.
Here is the link to the Issue:
https://github.com/cap-js/attachments/issues/97#issue-2474694865

Could you please review the content?

### Environment

```markdown
- **OS**:
- **Node**:
- **npm**:
- **cds-typer**: 
- **cds**:
```

**Comment by daogrady** [comment]
Hi @vc10812 ,

thanks for reporting this issue! It looks like we do not generate plural forms of aspects as of today. I will look into the matter.

Best,
Daniel

**Comment by daogrady** [comment]
Hi @vc10812  ,

I have prepared a [fix](https://github.com/cap-js/cds-typer/pull/421) for the issue.
Feel free to [try it out](https://github.com/cap-js/cds-typer/wiki/Trying-Out-Prerelease-Versions) before I merge and release it.

Best,
Daniel
