### ISSUE TITLE
[BUG] cds-typer does not generate ES module syntax with targetModuleType set to auto

### ISSUE THREAD

**Issue by AnsgarLichter** [cap-js/cds-typer#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

JavaScript

### Current Behavior

After initializing my project with the `esm`, the JS files of cds typer still use CJS syntax, though the package.json contains `type: module`:

```js
// This is an automatically generated file. Please do not change its contents manually!
const cds = require('@sap/cds')
const csn = cds.entities('AdminService')
// service
const AdminService = { name: 'AdminService' }
module.exports = AdminService
module.exports.AdminService = AdminService
// Books
module.exports.Book = { is_singular: true, __proto__: csn.Books }
module.exports.Books = csn.Books
// Authors
module.exports.Author = { is_singular: true, __proto__: csn.Authors }
module.exports.Authors = csn.Authors
// Languages
module.exports.Language = { is_singular: true, __proto__: csn.Languages }
module.exports.Languages = csn.Languages
// Genres
module.exports.Genre = { is_singular: true, __proto__: csn.Genres }
module.exports.Genres = csn.Genres
// Currencies
module.exports.Currency = { is_singular: true, __proto__: csn.Currencies }
module.exports.Currencies = csn.Currencies
// events
// actions
// enums
```

This is my package.json:
```json
{
  "name": "override",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^8",
    "express": "^4"
  },
  "devDependencies": {
    "@cap-js/sqlite": "^1",
    "@cap-js/cds-types": "^0.8.0",
    "@cap-js/cds-typer": ">=0.1",
    "@types/node": "^22.0.0",
    "typescript": "^5"
  },
  "scripts": {
    "start": "cds-serve",
    "watch": "cds-tsx w"
  },
  "type": "module",
  "sapux": [
    "app/admin-books",
    "app/browse"
  ],
  "imports": {
    "#cds-models/*": "./@cds-models/*/index.js"
  }
}
```

Once I add the following section to `package.json`, ES modules are used successfully:
```json
"cds": {
    "typer": {
      "target_module_type": "esm"
    }
  }
```

### Expected Behavior

When using the default setting `auto` for the `targetModuleType`, I expect es modules to be generated by cds-typer.

### Steps To Reproduce

1. cds init esm-test --add esm,typer,sample
2. cd esm-test
3. npm i
4. Execute a change in your data model and check the resulting JS files in `@cds-models`

### Environment

```markdown
- **OS**: macOS 15
- **Node**: 22.7.0
- **npm**: 10.9.0
- **cds-typer**: 0.30.0 
- **cds**: 8.5.1
```

### Anything else?

I read the documentation and checked the PR #398  for further guidance but I didn't find anything that was helpful to me.
Thank you in advance for your support!

**Comment by daogrady** [comment]
Hi Ansgar,

good catch! I have [prepared a fix](https://github.com/cap-js/cds-typer/pull/435).

Best,
Daniel

**Comment by AnsgarLichter** [comment]
Hi Daniel,

thanks for the quick response!
I tested your branch locally and I solves my issue.

Best,
Ansgar
