### ISSUE TITLE
[QUESTION] Deconstructed variables have type any

### ISSUE THREAD

**Issue by muellerj93** [cap-js/cds-typer#55]
### Question

Hi,

I saw cds-typer at this years reCAP and wanted to give it a try in one of my CAP Typescript projects.

I followed the steps mentioned in the [quickstart](https://cap.cloud.sap/docs/tools/cds-typer#cds-typer-vscode) and was able to install cds-typer, but to me it seems it doesn't work correctly.

I'm having the following difficulties:

1. Saving a `.cds` file doesn't autogenerate the types for me.
Using the CLI with npx however works and generates the @cds-models directory.
2. When I require and deconstruct my service definition (either via subpath or regular path) in my services init function, the variables are typed `any`.
If however I switch to an `import { ... } from 'path'` and move that to the top of my service implementations file, the variables are typed as `class`, but they don't work at runtime.

Additionally I had to tinker with some esilnt rules like (no-var-requires), to make my service syntactically correct, as well as add @cds-models to the eslint ignore list, but these shouldn't be causing above mentioned problems.

Is there anything obvious that I'm overlooking or not doing right?

Below are snippets of my `tsconfig.json` and `package.json` files, in case they might help:

```json
{
    "compilerOptions": {
        "target": "ES2022",
        "module": "CommonJS",
        "moduleResolution": "node",
        "skipLibCheck": true,
        "preserveConstEnums": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "noFallthroughCasesInSwitch": true,
        "noImplicitOverride": true,
        "noImplicitReturns": true,
        "noUncheckedIndexedAccess": true,
        "noPropertyAccessFromIndexSignature": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "exactOptionalPropertyTypes": true,
        "inlineSourceMap": true,
        "allowJs": false,
        "strict": true,
        "strictPropertyInitialization": false,
        "strictNullChecks": true,
        "forceConsistentCasingInFileNames": true,
        "paths": {
            "#cds-models/*": ["./@cds-models/*/index.ts"]
        },
        "rootDirs": ["./", "./@cds-models"]
    }
}
```

```json
{
  "name": "...",
  "version": "1.0.0",
  "description": "...",
  "private": true,
  "scripts": {
    ...
  },
  "dependencies": {
    "@sap-cloud-sdk/http-client": "^3.4.0",
    "@sap-cloud-sdk/util": "^3.4.0",
    "@sap/cds": "^7.1.1",
    "@sap/xssec": "^3.3.3",
    "express": "^4.18.2",
    "passport": "^0.6.0"
  },
  "devDependencies": {
    ...
    "@typescript-eslint/eslint-plugin": "^5.62.0",
    "@typescript-eslint/parser": "^5.62.0",
    ...
    "eslint": "^8.47.0",
    ...
    "typescript": "^5.1.6",
    "@cap-js/cds-typer": "^0.6.1"
  },
  "imports": {
    "#cds-models/*": "./@cds-models/*/index.ts"
  }
}
```

Thanks in advance for any help
Best regards

**Comment by daogrady** [comment]
Hi Jan,

1. depending on your version of the VSCode extension, there may be problems with auto-reloading after adding cds-typer to your project. Try to reload your VSCode window (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>P</kbd> > "Developer: Reload Window"), or restart your IDE. If that doesn't help, check the CDS output in the Output window and see if there are any messages related to cds-typer.
![Screenshot 2023-08-17 at 17 02 02](https://github.com/cap-js/cds-typer/assets/103028279/c8512760-284e-4a2b-ab86-3ce0152bfd0e)

2. having the imports all the way at the top of your file will fail as the corresponding runtime artefacts are not available when the file is being loaded. Could you instead try using the dynamic import syntax? E.g.:

```ts
const { Book, Author } = await import('#cds-models/sap/capire/bookshop')
```

Best,
Daniel

**Comment by muellerj93** [comment]
Hi,

thanks for the quick response.

Regarding 1.)
The output didn't show anything at all for me, which I thought was strange.
I checked the settings of the VSCode CDS Extension and found out, that the setting for CDS Typer was turned off for me.
After turning it on and reloading my VSCode window it works now.

<img width="610" alt="image" src="https://github.com/cap-js/cds-typer/assets/102537323/2c6ea616-2e61-4066-9c70-97c0562cd1df">

I don't know if this happens for other users as well, but maybe it's worth to put that in the documentation as a hint for troubleshooting.



Regarding 2.)
I'm pretty sure, that I've tried this yesterday and it didn't work.
Tried it today and now it does :D

Unfortunately I now have a small follow-up issue:

I've declared my event handlers as methods in my service class (see below):
![image](https://github.com/cap-js/cds-typer/assets/102537323/c13683fc-e406-47f2-9a6a-1b41a057b59b)

So I used the JSDoc comment to remedy the LSP not being able to infer my type, but the data object in the request still shows up as any.
![image](https://github.com/cap-js/cds-typer/assets/102537323/3f1fdef7-c29f-4904-983f-61706b55cb71)

CDSRequest in this case is a type-alias for Request of the CDS Framework (since Request is already a global in Node.js)

As the approach above didn't work, I've tried to directly declare req as `TypedRequest<T>`.
I managed to make this work by redundantly importing the required type at the top of my file with an alias and passing that for T.

Do you have a better solution for this, than my approach? (dynamic import in init() to have the runtime work + redundant import with alias)

Thanks again :)

**Comment by daogrady** [comment]
Hi Jan,

thanks for the hint, I will make sure to mention the VSCode option in CAPire.

Regarding your follow-up:
I am afraid the solution you found is probably the best one for now. The JSDoc annotation were meant for JS projects where there is no type declared for the `req` parameter. As you can annotate the type in TS projects directly, you'd probably have to do:

```ts
import type { Book } from '#cds-models/sap/capire/bookshop'

// ...

handler (req: TypedRequest<Book>) { ... }
```

by doing an `import type` you'd at least make sure to contain the redundancy to design time. In that case it's also no problem that the import takes place outside the service implementation, as only the runtime side of the imports causes issues for such constellations.

Best,
Daniel

**Comment by muellerj93** [comment]
Ok, then I'll handle it this way.
Thanks again for your help :)
