### ISSUE TITLE
[IMPROVEMENT] Remove `.drafts` Property From Entities That Are Not Actually Draftable

### ISSUE THREAD

**Issue by daogrady** [cap-js/cds-typer#68]
Follow-up to: https://github.com/cap-js/cds-typer/issues/34

`.drafts` should only be present in entities that can actually be draftable. Currently, entities that aren't actually draftable might end up with a `.drafts` property.

- [ ] check with the compiler team whether there is a surefire way to determine an entity's draftability
- [ ] if possible, get rid of the current voodoo where we propagate annotations through the CSN
- [ ] make sure a static `.drafts` property is only exposed when the entity can actually be drafted during runtime

**Comment by stockbal** [comment]
Hi Daniel,

there is a way to get the sql csn with `cds.compile.for.sql` and the inferred csn.

```js
const inferred = await cds.linked(await cds.load(paths, { docs: true }))
const sql = cds.compile.for.sql(inferred)
```

This will  produce something like
![image](https://github.com/user-attachments/assets/884b0c4c-7d1b-4632-8a35-87d9751b4afe)

We can just take the `.drafts` suffixed entries, remove the suffix and we have entities that should get the `drafts` property.

I implemented it in this [branch](https://github.com/stockbal/cds-typer/tree/refactor/replace-classes-with-types) of my fork.

P.S.: There is a lot more going on in that branch, so you may have to overlook a few things 😉. If you think that we can use that approach I am happy to create a specific PR for the drafts feature only.
