### ISSUE TITLE
[QUESTION] Receiving an usual error from TypeScript when I try and reference things with strings

### ISSUE THREAD

**Issue by jbm1991** [cap-js/cds-typer#72]
### Question

Hi,

In my code, anywhere that I'm using a string to retrieve an object I am getting an error. I haven't raised this as a bug, as I feel it's probably something I've done wrong, but any help would be appreciated. The only thing that makes me think it might a bug and/or missing functionality is that it's happening to all of my entities where I'm doing, rather than just one.

Thanks in advance
John

Example code:
```ts
const result = (await this.getExample1(regNo)) as Example1;
const value = result[endpoint.path]; //endpoint.path is a string
```

Error received:
```bash
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Example1'.
No index signature with a parameter of type 'string' was found on type 'Example1'.
```

CDS of `Example1` from schema
```cds
entity Example1s {
  key ID            : String(10);
      example2  : Decimal;
      example3  : Decimal;
}
```

Type of `Example1`
```ts
export function _Example1Aspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Example1 extends Base {
        ID?: string;
        example2?: number;
        example3?: number;
  };
}
export class Example1 extends _Example1Aspect(__.Entity) {}
export class Example1s extends Array<Example1> {}
```

**Comment by daogrady** [comment]
Hi John,

your use case seems to be that you are trying to dynamically access properties of an `Example1` instance, if I am not mistaken.

The issue there is that `endpoint.path` could be any string, not just one of the valid keys for `Example1`. If you can somehow ensure that `endpoint.path` always is one of `ID`, `example2`, or `example3`, then the type system should comply.

For example:

```ts
const result = (await this.getExample1(regNo)) as Example1;
const key = endpoint.path as 'ID' | 'example2' | 'example3'
const value = result[key];
```

should be fine.
Please let me know if this helped you solve the issue.

Best,
Daniel

**Comment by jbm1991** [comment]
Hi Daniel,

Thanks again for the quick response. That has worked perfectly, thank you very much!

Thanks
John
