### ISSUE TITLE
[BUG] Typer crashes on basic cds model

### ISSUE THREAD

**Issue by fabiantschirschnitz** [cap-js/cds-typer#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior
```
TypeError: Cannot read properties of undefined (reading 'name')
    at #getDraftable (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\csn.js:46:39)
    at propagate (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\csn.js:73:58)
    at #propagateProjections (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\csn.js:80:13)
    at DraftUnroller.unroll (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\csn.js:118:35)
    at unrollDraftability (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\csn.js:159:25)
    at amendCSN (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\csn.js:263:5)
    at new Visitor (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\visitor.js:63:9)
    at compileFromCSN (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\compile.js:67:23)
    at compileFromFile (C:\Users\Tschirschnitz\git\issue-cds-typer\node_modules\@cap-js\cds-typer\lib\compile.js:49:12)
```

### Expected Behavior

Hey cds-typer-Team,

I encountered a strange Exception today while generating types on a quite simple model. See example and repo below. Is there something wrong with my model? `cds-ts serve` works great with the example.

Kind regards, Fabian

### Steps To Reproduce

```cds
service main_service {

  entity CarsProducer as projection on db.CarsProducer;
  entity CarsModels   as projection on db.CarsProducer.model;
  //### Basic F4
  annotate CarsModels with @cds.odata.valuelist;
  annotate CarsModels with @UI.Identification: [{Value: name}];

};
```

Just run `npm run cds-typer` on the example repo, please.

### Environment

```markdown
- **OS**: Windows
- **Node**: v18.16.1
- **npm**: 9.5.1
- **cds-typer**: 0.10.0
- **cds**: 7.2.1
```

### Repository Containing a Minimal Reproducible Example

https://github.com/fabiantschirschnitz/issue_cds_typer

**Comment by fabiantschirschnitz** [comment]
fyi @nlaenger

**Comment by daogrady** [comment]
Hi Fabian,

I have added a fix for this issue in https://github.com/cap-js/cds-typer/pull/80 which I will include in the next release.
Feel free to try if it fixes the problem in your model.

Best,
Daniel

**Comment by fabiantschirschnitz** [comment]
Great thx, I will have a look.

**Comment by fabiantschirschnitz** [comment]
Hey Daniel,

I tried your fix and indeed there is no exception thrown anymore. Thank you.
However I was curious if the generated types are as I would expect.

I was surprised that the generated type for `CarModels` had no properties. So I changed the service definition to explicitly have the desired fields: 
```cds
service main_service {

  entity CarsProducer as projection on db.CarsProducer;

  entity CarsModels   as projection on db.CarsProducer.model {
    up_,
    code,
    name
  };
...
```
Still I am getting an 'empty' class definition: 
```typescript
export function _CarsModelAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class CarsModel extends Base {
    static actions: {
    }
  };
}
export class CarsModel extends _CarsModelAspect(__.Entity) {}
```
Is this as expected, or would you also want to have `code` and `name` as properties of the type?

fyi @nlaenger

**Comment by daogrady** [comment]
Hi Fabian,

this seems to be another issue with the use of inline definitions (in this case a projection on an indirect reference to a type that is declared inline).
I will add this to the backlog, but it I don't see a hotfix for this at the moment, so it will probably take a while before I get to work on it.

If I am not mistaken, then pulling this anonymous type from `CarsProducer` into an explicit, named type would help:

```patch
// replace_me.cds
+entity Models {
+    key code : String(10);
+        name : String(40);
+}

@cds.autoexpose
entity CarsProducer : managed {
    key ID    : String(40);
        @mandatory
        name  : String(80);
-        model: Composition of many {
-          key code : String(10);
-            name : String(40);
-        }
+        model : Composition of many Models;
}


// main_service.cds
-  entity CarsModels   as projection on db.CarProducer.model;
+  entity CarsModels   as projection on db.Models;
```

Would this be an acceptable interim solution?

Best,
Daniel

**Comment by fabiantschirschnitz** [comment]
Hey Daniel, yeah that does the job in the meanwhile. Thanks for your instant support! Have a nice weekend.

**Comment by daogrady** [comment]
Hi Fabian,

glad I could help! 🙂 I will track the remaining issue in https://github.com/cap-js/cds-typer/issues/81

Have a great weekend too!

Best,
Daniel
