### ISSUE TITLE
[FEATURE] Refinement of Type Generation in CDS-Typer for Optional / Nullable Fields

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-typer#87]
### Question

# Background
When using the CDS-Typer tool to generate TypeScript types for SAP CAP CDS services, it's observed that the tool does not explicitly differentiate between fields that can be null and those that can't. This becomes particularly problematic when TypeScript's [exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) is enabled.

# Current Behavior
Both the following CDS definitions for getUserDetails() yield the TypeScript type `example?: string;`, even though one specifies nullability:

```cds
function getExample() returns {
    [...]
    example : String;
    [...]
};
```

```cds
function getExample() returns {
    [...]
    example : String null;
    [...]
};
```

# Expected Behavior
The type generation should be more specific. For instance, a more explicit type definition like `example?: string | null`; would be more informative and compatible with exactOptionalPropertyTypes.

> [!NOTE]
> I'm uncertain on the handling of undefined properties. It might also make sense to check whether ` example?: string | undefined` is an option for the first, `example?: string | undefined | null` for the second case.

**Comment by daogrady** [comment]
Hi @siarhei-murkou,

it is currently not explicitly planned, as other more pressing matters need to be addressed first.
Though you are welcome to submit a PR, if you see a solution. 🙂

Regarding `:?`: there is a [CLI option `--propertiesOptional false`](https://cap.cloud.sap/docs/tools/cds-typer#typer-cli), although its behaviour is not really supported. Not sure if that helps you.

Best,
Daniel

**Comment by siarhei-murkou** [comment]
Hi @daogrady ,

Thanks, `--propertiesOptional false` improves the TS validation much stronger. 👍 

The only missing part is to compile nullable fields to TS prop `propName: ... | null` in order to not manually redefine auto-compiled TS classes/types. But as you said, `... | null` enhancement is not in your current roadmap.
If so, I'll try to take a look at this lib implementation a bit later and investigate how to add this extra logic 🙂

**Comment by tsteckenborn** [comment]
Hi you two,

As both `null` and `undefined` signal absent or uninitialized values - although in theory for different reasons - in case you're heading for it @siarhei-murkou, would we strife for `... | null` or `... | null | undefined`?

**Comment by daogrady** [comment]
Hi @tsteckenborn ,

just wanted to let you know @siarhei-murkou is currently working on a [PR](https://github.com/cap-js/cds-typer/pull/108) to introduce the nullable behaviour.
The current approach is to have `... | null` for all nullable fields. Do you have an opinion on that?

Best,
Daniel

**Comment by tsteckenborn** [comment]
Hi @daogrady ,

Yeah I saw that. I'm currently not quite sure on how I'd interpret the absence of values (indicated by not having not null or mandatory) in CDS. In general both `undefined` and `null` indicate the absence of values - even though for different reasons.

With TypeScript recommending enabling the option "exactOptionalPropertyTypes" I'd rather opt for allowing both. That seems to be handled fine when ignoring the types. Yet as said I'm currently not sure about it and tend to think that I think this way because I'd like it and currently need to do some workarounds...
