### ISSUE TITLE
[BUG] App crashes with unused enum types

### ISSUE THREAD

**Issue by rgrenz** [cap-js/cds-typer#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When defining an enum type that is then not used anywhere in CDS (but possibly used in TS), an appropriate type is generated by cds-typer but the app then crashes on startup.

```bash
cds-ts watch
...
TypeError: Cannot read properties of undefined (reading 'enum')
```

### Expected Behavior

The app should not crash on startup.

### Steps To Reproduce

```cds
// stuff.cds
namespace stuff;
type Language : String enum {
    DE = 'German';
    EN = 'English'
}

// do not use Language in any entity or service definition
```
```ts
// test-service.ts
import { Language } from "#cds-models/stuff"; //  TypeError: Cannot read properties of undefined (reading 'enum') 
console.log(Language);
```

### Environment

```markdown
@cap-js/cds-typer: 0.11.1
| Node.js                | v18.18.0    |
| @sap/cds               | 7.3.0       |
| @sap/cds-compiler      | 4.3.0       |
| @sap/cds-dk            | -- missing  |
| @sap/cds-dk (global)   | 7.2.0       |
| @sap/eslint-plugin-cds | 2.6.3       |
| @sap/cds-mtxs          | 1.11.0      |
```

### Repository Containing a Minimal Reproducible Example

https://github.com/rgrenz/cds-typer-issue/tree/unused-enum-generation

### Anything else?

This might be an upstream issue/feature where @sap/cds "optimizes" the source and throws away any types that are unused in CDS. A workaround is to define a dummy entity where the enum is used (see example repo).

**Comment by daogrady** [comment]
Hi Rouven,

thanks for the report, yet another good find! I am currently looking into the matter. Out of curiosity: could you give a use case where an enum is not used throughout the model but still required at runtime? We talked about this issue today and were a bit stumped how one would make use of these enums.

Best,
Daniel

**Comment by rgrenz** [comment]
Hi Daniel, thank you for looking into the issue! 

In our case, we need these enums when communicating with another service. We need to send requests with specific parameters (that can have any of the values of the enum). However, internally these values mean nothing to our CAP application, so persisting them in our DB would provide no benefit to us. However, we would still like to keep the definition in CDS to have the full data model in one place.

**Comment by daogrady** [comment]
Hi Rouven,

thanks for shedding some light on this. I am wondering if the enum is in that case really part of your model or should rather be part of your business logic (read: an enum defined in your service implementation that calls the remote service), as this is information that is specific to the remote service.
But regardless, I will forward this use case to let runtime know that this is an application for enums that exists "in the wild". 🙂

I have finished [the PR](https://github.com/cap-js/cds-typer/pull/107) that addresses this issue. Feel free to check if it fixes the problem in your actual model before I merge it.

Best,
Daniel
