### ISSUE TITLE
[BUG] Allow Readable as a return type for actions LargeBinary

### ISSUE THREAD

**Issue by RalfSchoenfeld** [cap-js/cds-typer#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Action definition:
`action generateDocument(templateId : String, documentContext : String) returns @Core.MediaType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' LargeBinary`

Generated Types:
`export declare const generateDocument: { (templateId: string, documentContext: string): Buffer | string, __parameters: {templateId: string, documentContext: string}, __returns: Buffer | string };`

Documentation:
https://cap.cloud.sap/docs/node.js/best-practices#custom-streaming-beta
https://nodejs.org/api/stream.html#class-streamreadable

### Expected Behavior

Generated Types:
`export declare const generateDocument: { (templateId: string, documentContext: string): Buffer | string | Readable, __parameters: {templateId: string, documentContext: string}, __returns: Buffer | string | Readable };`

### Steps To Reproduce

Action definition:
`action generateDocument(templateId : String, documentContext : String) returns @Core.MediaType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' LargeBinary`

Try to return a Readable in the action implementation.

### Environment

```markdown
- **OS**: Ubuntu 22.04
- **Node**: v18.16.1
- **npm**: 9.5.1
- **cds-typer**: 0.11.1
- **cds**: 7.3.0
```

**Comment by daogrady** [comment]
Hi Ralf,

thanks for suggesting this change. If I am reading the docs you linked correctly, the return type would need to be `... | { value: Readable }`, rather than `... | Readable`, correct?

Best,
Daniel

**Comment by RalfSchoenfeld** [comment]
Hi Daniel, yes that's correct and also the other string properties like $mediaContentType. Thank you!

**Comment by daogrady** [comment]
Hi Ralf,

I have opened [a PR](https://github.com/cap-js/cds-typer/pull/105) which addresses this issue. Feel free to check if it fixes the problem in your specific project before the merge.

Best,
Daniel
