### ISSUE TITLE
[BUG] Enum values all undefined

### ISSUE THREAD

**Issue by sebbi08** [cap-js/cds-typer#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When the projects get build and run in production, the ENUM values are all undefined.
![image](https://github.com/cap-js/cds-typer/assets/9070136/4d95e626-4702-49fa-9c52-017920dadd85)

this seems to be an issue with the generation of the enum in the index.js of the by cds-typer generated code

![image](https://github.com/cap-js/cds-typer/assets/9070136/4361178f-8bf7-4e4a-9c7c-99658af17838)

### Expected Behavior

The ENUM should be populated

### Steps To Reproduce

1. clone the project : https://github.com/sebbi08/cds-typer-issue/tree/bug-enum
2. debug `npm run start` and inspect the value if `a` in the `test-service.ts`

### Environment

```markdown
- **OS**: Ubuntu
- **Node**: 18.18.0
- **npm**: 9.8.1
- **cds-typer**: 0.11.1
- **cds**:
|:---------------------- | ----------- |
| Node.js                | v18.18.0    |
| @sap/cds               | 7.2.0       |
| @sap/cds-compiler      | 4.2.2       |
| @sap/cds-dk            | 7.2.0       |
| @sap/cds-dk (global)   | 7.2.0       |
| @sap/eslint-plugin-cds | 2.6.3       |
| @sap/cds-mtxs          | 1.11.0      |
```

### Repository Containing a Minimal Reproducible Example

https://github.com/sebbi08/cds-typer-issue/tree/bug-enum

**Comment by stockbal** [comment]
Hi @sebbi08,

I tested your scenario with `@sap/cds@7.31` and it worked. If it is possible in your project I would upgrade to this cds version.

Regards,
Ludwig

**Comment by sebbi08** [comment]
Hi,

for the event with version 7.3.1 it is now working

may it be a problem that we defined the enum like this 
```cds
type MyEnum : String enum {
    MyEnumA;
    MyEnumB;
}
```
if i add the values like

```cds
type MyEnum : String enum {
    MyEnumA = 'MyEnumA';
    MyEnumB = 'MyEnumB';
}
```

it seams to work

**Comment by daogrady** [comment]
Hi Sebastian,

thanks for reporting this issue, and also thank you, Ludwig, for checking in on the matter.
I have modified the enum extraction logic to use the field's name as fallback value. This should address the issue.
If you would like to verify the fix before the next release, you can check it out [here](https://github.com/cap-js/cds-typer/pull/104).

Best,
Daniel
